--- BONDECOMMANDE_CLIENT_FILLE_CPL NAPIANA client;date;etat
CREATE OR REPLACE FORCE VIEW "ASYNCARTISANAT"."BONDECOMMANDE_CLIENT_GLOBALE" ("ID", "IDBC", "IDDEVISE", "MONTANT", "PRODUIT", "PU", "QUANTITE", "REMISE", "TVA", "UNITE", "QTEOF", "QTEOFRESTANTE", "QTEFAB", "QTEFABRESTANTE", "QTELIVRE", "QTENONLIVRE", "LIBELLEPRODUIT", "IDCLIENT", "IDCLIENTLIB", "DATY", "ETAT", "ETATLIB") AS 
  SELECT BCFC."ID",BCFC."IDBC",BCFC."IDDEVISE",BCFC."MONTANT",BCFC."PRODUIT",BCFC."PU",BCFC."QUANTITE",BCFC."REMISE",BCFC."TVA",BCFC."UNITE",BCFC."QTEOF",BCFC."QTEOFRESTANTE",BCFC."QTEFAB",BCFC."QTEFABRESTANTE",BCFC."QTELIVRE",BCFC."QTENONLIVRE",BCFC."LIBELLEPRODUIT",bc.IDCLIENT,bc.IDCLIENTLIB , bc.DATY,bc.ETAT , bc.ETATLIB  FROM 
	BONDECOMMANDE_CLIENT_FILLE_CPL bcfc
	JOIN BONDECOMMANDE_CLIENT_CPL bc ON bc.ID = BCFC.IDBC
	;

-- BC_GROUPE PAR INGREDIENT
CREATE OR REPLACE FORCE VIEW BC_GROUPE_ING AS
    SELECT
    LISTAGG(ID || ':' || QTEOFRESTANTE, ';') WITHIN GROUP (ORDER BY ID) AS BCLIST,
    PRODUIT,
    LIBELLEPRODUIT,
    LISTAGG(IDCLIENTLIB , ';') WITHIN GROUP (ORDER BY ID) AS CLIENTLIST,
    SUM(QTEOFRESTANTE) AS QTEOFRESTANTE
    FROM
    ASYNCARTISANAT.BONDECOMMANDE_CLIENT_GLOBALE
    WHERE
    QTEOFRESTANTE > 0
    GROUP BY
    PRODUIT,
    LIBELLEPRODUIT;

-- RECETTE AVEC CAT
CREATE OR REPLACE FORCE VIEW AS_RECETTE_LIB_CAT AS
SELECT arl.*,c.ID AS CATEGORIEINGREDIENT , c.VAL AS categorielib, ai.COMPTE_VENTE ,ai.COMPTE_ACHAT  FROM 
	AS_RECETTE_LIBCOMPLET arl 
	JOIN AS_INGREDIENTS ai ON ai.id = arl.IDINGREDIENTS 
	JOIN CATEGORIEINGREDIENT c ON c.ID = ai.CATEGORIEINGREDIENT ;
