CREATE OR REPLACE FORCE VIEW "CARTONFILLE_CPL"  AS
  select cf.ID,
 		cf.IDMERE,
 		cf.IDINGREDIENT,
 		cf.QUANTITE,
 		cf.REMARQUE,
 		cf.IDBCFILLE,
 		ai.libelle AS PRODUITLIB

       from CARTONFILLE cf
   LEFT JOIN AS_INGREDIENTS ai ON cf.IDINGREDIENT = ai.ID;


  CREATE OR REPLACE FORCE VIEW "AS_BONCOMMANDE_FILLE_AVEC_PRIX" AS
  SELECT
    bc.ID,
    bc.PRODUIT,
    bc.IDMERE,
    bc.QUANTITE,
    bc.UNITE,
    CAST(ai.PV AS NUMBER(20, 2)) AS pu,
    CAST(ai.TVA AS NUMBER(20, 2)) AS tva,
    ai.COMPTE_VENTE,ai.COMPTE_ACHAT
FROM
    BONDECOMMANDE_CLIENT_FILLE bC
LEFT JOIN AS_INGREDIENTS ai
    ON ai.ID = bl.PRODUIT;

   ALTER TABLE AS_BONDECOMMANDE_FILLE DROP  CONSTRAINT AS_BONDECOMMANDE_FILLE;


UPDATE MENUDYNAMIQUE
SET HREF='module.jsp?but=bondelivraison/bondelivraison-liste.jsp'
WHERE ID='MNDN001804006';

CREATE OR REPLACE  VIEW UPDATEVENTEDETAILS (ID, IDVENTE, IDPRODUIT, IDPRODUITLIB, IDORIGINE, QTE, PU, REMISE, TVA, PUACHAT, PUVENTE, IDDEVISE, TAUXDECHANGE, DESIGNATION, COMPTE) AS
  SELECT
vd.ID,
vd.IDVENTE,
vd.IDPRODUIT,
p.LIBELLE AS idProduitLib,
vd.IDORIGINE,
vd.QTE,
vd.PU,
vd.REMISE,
vd.TVA,
vd.PUACHAT,
vd.PUVENTE,
vd.IDDEVISE,
vd.TAUXDECHANGE,
vd.DESIGNATION,
vd.COMPTE
FROM
VENTE_DETAILS vd
LEFT JOIN AS_INGREDIENTS p ON
p.ID = vd.IDPRODUIT;

ALTER TABLE AS_BONDELIVRAISON DROP CONSTRAINT BL_MAGASIN_FK;

ALTER TABLE AS_BONDELIVRAISON ADD  CONSTRAINT BL_MAGASIN_FK FOREIGN KEY (MAGASIN)
	  REFERENCES POINT(ID) ;

ALTER TABLE AS_BONDECOMMANDE_FILLE DROP  CONSTRAINT BCF_PRODUIT;

ALTER TABLE AS_BONDECOMMANDE_FILLE ADD  CONSTRAINT BCF_PRODUIT FOREIGN KEY (PRODUIT)
	  REFERENCES AS_INGREDIENTS (ID)


CREATE OR REPLACE  VIEW BONDECOMMANDE_CLIENT_CPL (ID, DATY, ETAT, REMARQUE, DESIGNATION, MODEPAIEMENT, MODEPAIEMENTLIB, IDCLIENT, IDCLIENTLIB, REFERENCE, IDMAGASINLIB, ETATLIB) AS
  SELECT
bc.ID,
bc.DATY,
bc.ETAT,
bc.REMARQUE,
bc.DESIGNATION,
bc.MODEPAIEMENT,
m.VAL AS MODEPAIEMENTLIB,
bc.IDCLIENT,
c.NOM AS IDCLIENTLIB,
bc.REFERENCE,
m2.VAL AS IDMAGASINLIB,
CASE
    WHEN bc.ETAT = 0 THEN '<span style=color: green;>ANNULEE</span>'
    WHEN bc.ETAT = 1 THEN '<span style=color: green;>CREE</span>'
    WHEN bc.ETAT = 11 THEN '<span style=color: green;>VALIDEE</span>'
END AS ETATLIB

FROM BONDECOMMANDE_CLIENT bc
LEFT JOIN CLIENT c ON c.id = bc.IDCLIENT
LEFT JOIN MODEPAIEMENT m ON m.id = bc.MODEPAIEMENT
LEFT JOIN MAGASIN m2 ON m2.id = bc.IDMAGASIN

--parent key not found
ALTER TABLE AS_BONDECOMMANDE_FILLE ADD CONSTRAINT as_BCFILLE_UNITE_FK  FOREIGN KEY (UNITE)
	  REFERENCES  AS_UNITE (ID)
 ;



 CREATE OR REPLACE  VIEW FABRICATIONFILLECPL (ID, IDINGREDIENTS, LIBELLE, REMARQUE, IDMERE, DATYBESOIN, QTE, IDUNITE, PU, IDINGREDIENTSLIB, OPERATEUR,IDUNITELIB) AS
  SELECT
f.ID,f.IDINGREDIENTS,f.LIBELLE,f.REMARQUE,f.IDMERE,f.DATYBESOIN,f.QTE,f.IDUNITE,f.PU,
ai.LIBELLE AS idingredientsLib,
p.NOM || ' - ' || p.TELEPHONE as operateur,
au.val AS IDUNITELIB
FROM FABRICATIONFILLE f
LEFT JOIN AS_INGREDIENTS ai ON ai.id = f.IDINGREDIENTS
left join PERSONNEL p on p.ID = f.OPERATEUR
LEFT JOIN AS_UNITE au ON au.id = f.IDUNITE ;


CREATE OR REPLACE  VIEW AS_BONLIVRFILLE_CLIENT_CPL (ID, PRODUIT, NUMBL, QUANTITE, IDVENTEDETAIL, UNITE, IDBC_FILLE, IDPRODUITLIB, IDVENTE, IDBC, QTELIVREE, QTERESTEALIVRER) AS
  SELECT
	abcf.ID,
	abcf.PRODUIT,
	abcf.NUMBL,
	abcf.QUANTITE,
	abcf.IDVENTEDETAIL,
	abcf.UNITE,
	abcf.IDBC_FILLE,
	p.LIBELLE AS idproduitlib,
	vd.idvente,
	abc.idbc,
	CAST(nvl(s.qtelivree ,0)AS NUMBER(30,2)) AS qtelivree,
	CAST(nvl(abcf.QUANTITE - CAST(nvl(s.qtelivree ,0)AS NUMBER(30,2))  ,0)AS NUMBER(30,2)) AS qteResteALivrer
FROM AS_BONDELIVRAISON_CLIENT_FILLE abcf
LEFT JOIN as_ingredients p ON p.id = abcf.produit
LEFT JOIN VENTE_DETAILS vd ON vd.id = abcf.IDVENTEDETAIL
LEFT JOIN AS_BONDELIVRAISON_CLIENT abc ON abc.id = abcf.numbl
LEFT JOIN sortiestockfille s ON s.IDPRODUIT = abcf.produit AND s.IDVENTEDETAIL =abcf.IDVENTEDETAIL



DELETE FROM AS_BONDECOMMANDE_FILLE;

ALTER TABLE AS_BONDELIVRAISON_FILLE DROP CONSTRAINT BLF_UNITE_FK;


ALTER TABLE AS_BONDELIVRAISON_FILLE ADD  CONSTRAINT BLF_UNITE_FK FOREIGN KEY (UNITE)
	  REFERENCES AS_UNITE(ID)


ALTER TABLE AS_BONDELIVRAISON_FILLE ADD  CONSTRAINT BLF_PRODUIT_FK FOREIGN KEY (PRODUIT)
	  REFERENCES AS_INGREDIENTS(ID)


CREATE OR REPLACE FORCE VIEW "ASYNCARTISANAT"."CARTONFILLE_CPL" AS
  select cf.ID,
 		cf.IDMERE,
 		cf.IDINGREDIENT,
 		cf.QUANTITE,
 		cf.REMARQUE,
 		cf.IDBCFILLE,
 		ai.libelle AS PRODUITLIB,
		c.IDBC AS IDBC
       from CARTONFILLE cf
   LEFT JOIN AS_INGREDIENTS ai ON cf.IDINGREDIENT = ai.ID
   LEFT JOIN CARTON c ON cf.IDMERE = c.ID;


CREATE OR REPLACE VIEW  BonCommandeDetailsCarton_Cpl as
SELECT
bc.ID ,
bc.idbc AS idbc ,
ai.LIBELLE AS produitlib,
ai.id AS produit,
nvl(bc.QUANTITE,0) AS quantitebf ,
nvl(c.QUANTITE,0) AS quantitecf,
nvl(bc.QUANTITE,0) - nvl(c.QUANTITE,0) AS restecf
FROM BONDECOMMANDE_CLIENT_FILLE bc
LEFT JOIN CARTONFILLE c  ON c.IDBCFILLE = bc.ID
LEFT JOIN AS_INGREDIENTS ai ON ai.ID = bc.PRODUIT
GROUP BY bc.ID, bc.idbc, ai.LIBELLE, ai.id, bc.QUANTITE, c.QUANTITE;


CREATE OR REPLACE FORCE VIEW "ASYNCARTISANAT"."PRODUITCOMMANDEFILLECARTON" ("ID", "IDBC", "PRODUITLIB", "PRODUIT", "QUANTITEBCF", "QUANTITECARTONFILLE", "RESTECARTONFILLE") AS
  SELECT
bc.ID ,
bc.idbc AS idbc ,
ai.LIBELLE AS produitlib,
ai.id AS produit,
nvl(bc.QUANTITE,0) AS quantiteBCF ,
nvl(c.QUANTITE,0) AS quantitecartonfille,
nvl(bc.QUANTITE,0) - nvl(c.QUANTITE,0) AS restecartonfille
FROM BONDECOMMANDE_CLIENT_FILLE bc
LEFT JOIN CARTONFILLE c  ON c.IDBCFILLE = bc.ID
LEFT JOIN AS_INGREDIENTS ai ON ai.ID = bc.PRODUIT
GROUP BY bc.ID, bc.idbc, ai.LIBELLE, ai.id, bc.QUANTITE, c.QUANTITE;



SELECT * FROM BonCommandeDetailsCarton_Cpl




CREATE OR REPLACE VIEW VUE_SUIVI_CARTON AS
SELECT
    bcf.ID AS id,
    bcf.IDBC AS idbc_mere,
    ai.LIBELLE AS produitlib,
    ai.ID AS produit,
    ai.UNITE AS unite,
    NVL(bcf.QUANTITE, 0) AS quantitebcf,
    NVL(SUM(cf.QUANTITE), 0) AS quantitecartonfille,
    NVL(bcf.QUANTITE, 0) - NVL(SUM(cf.QUANTITE), 0) AS restecartonfille
FROM BONDECOMMANDE_CLIENT_FILLE bcf
LEFT JOIN CARTONFILLE cf ON cf.IDBCFILLE = bcf.ID
LEFT JOIN CARTON c ON c.ID = cf.IDMERE AND c.ETAT > 11
LEFT JOIN AS_INGREDIENTS ai ON ai.ID = bcf.PRODUIT
GROUP BY
    bcf.ID,
    bcf.IDBC,
    ai.LIBELLE,
    ai.ID,
    ai.UNITE,
    bcf.QUANTITE;




CREATE OR REPLACE VIEW VUE_CARTONFILLE_SUM AS
SELECT
  cf.IDBCFILLE,
  SUM(cf.QUANTITE) AS QUANTITE_CARTONFILLE
FROM CARTONFILLE cf
JOIN CARTON c ON c.ID = cf.IDMERE AND c.ETAT >= 11
GROUP BY cf.IDBCFILLE;

CREATE OR REPLACE VIEW VUE_CARTONFILLE_IDMERE AS
SELECT
  cf.IDBCFILLE,
  MIN(cf.IDMERE) AS ID_CARTON_MERE
FROM CARTONFILLE cf
JOIN CARTON c ON c.ID = cf.IDMERE AND c.ETAT >= 11
GROUP BY cf.IDBCFILLE;

CREATE OR REPLACE VIEW VUE_SUIVI_CARTON_LIVRAISON AS
SELECT
    bcf.ID AS id,
    bcf.IDBC AS idbc_mere,
    vci.ID_CARTON_MERE AS idCartonMere,
    ai.ID AS produit,
    ai.LIBELLE AS produitlib,
    ai.UNITE AS unite,
    NVL(bcf.QUANTITE, 0) AS quantitebcf,
    NVL(vc.QUANTITE_CARTONFILLE, 0) AS quantitecartonfille,
    NVL(bcf.QUANTITE, 0) - NVL(vc.QUANTITE_CARTONFILLE, 0) AS restecartonfille
FROM BONDECOMMANDE_CLIENT_FILLE bcf
LEFT JOIN AS_INGREDIENTS ai ON ai.ID = bcf.PRODUIT
LEFT JOIN VUE_CARTONFILLE_SUM vc ON vc.IDBCFILLE = bcf.ID
LEFT JOIN VUE_CARTONFILLE_IDMERE vci ON vci.IDBCFILLE = bcf.ID;