ALTER TABLE OFAB 
ADD  idbc varchar2(500);


ALTER TABLE OFFILLE 
ADD idbcfille varchar2(1000);

ALTER TABLE FABRICATION 
ADD idbc varchar2(500);

ALTER TABLE FABRICATIONFILLE 
ADD idbcfille varchar2(1000);

ALTER TABLE FABRICATIONFILLE 
ADD operateur varchar2(255);

ALTER TABLE BONDECOMMANDE_CLIENT 
ADD datebesoin date;


ALTER TABLE OFAB 
ADD CONSTRAINT fk_ofab_bdc FOREIGN KEY (IDBC) 
REFERENCES BONDECOMMANDE_CLIENT(ID);

ALTER TABLE OFFILLE 
ADD CONSTRAINT fk_offille_bdcfile FOREIGN KEY (IDBCFILLE) 
REFERENCES BONDECOMMANDE_CLIENT_FILLE(ID);


ALTER TABLE FABRICATION 
ADD CONSTRAINT fk_fabrication_bdc FOREIGN KEY (IDBC) 
REFERENCES BONDECOMMANDE_CLIENT(ID);

ALTER TABLE FABRICATIONFILLE 
ADD CONSTRAINT fk_fabfille_bdcfille FOREIGN KEY (IDBCFILLE) 
REFERENCES BONDECOMMANDE_CLIENT_FILLE(ID);

ALTER TABLE FABRICATIONFILLE 
ADD CONSTRAINT fk_fabfille_operateur FOREIGN KEY (operateur) 
REFERENCES personnel(ID);


--2025-04-16 - 14:30
CREATE OR REPLACE FORCE VIEW "BONDECOMMANDE_CLIENT_CPL" AS
  SELECT
bc.ID,
bc.DATY,
bc.ETAT,
bc.REMARQUE,
bc.DESIGNATION,
bc.MODEPAIEMENT,
m.VAL AS MODEPAIEMENTLIB,
bc.IDCLIENT,
c.NOM AS IDCLIENTLIB,
bc.REFERENCE,
m2.VAL AS IDMAGASINLIB,
CASE
    WHEN bc.ETAT = 0 THEN '<span style="color: green;">ANNULEE</span>'
    WHEN bc.ETAT = 1 THEN '<span style="color: green;">CREE</span>'
    WHEN bc.ETAT = 11 THEN '<span style="color: green;">VALIDEE</span>'
END AS ETATLIB

FROM BONDECOMMANDE_CLIENT bc
LEFT JOIN CLIENT c ON c.id = bc.IDCLIENT
LEFT JOIN MODEPAIEMENT m ON m.id = bc.MODEPAIEMENT
LEFT JOIN MAGASIN2 m2 ON m2.id = bc.IDMAGASIN ;




--- 15:40 AS_RECETTEBC

create view AS_RECETTEBC as
select offi.id,offi.idbc as IDPRODUITS,offi.PRODUIT as idingredients,
cast(cast(offi.quantite as number(20,2))*cast(nvl(e.qte,1) as number(20,2)) as number(20,2)) as quantite,ing.unite,ing.compose from BONDECOMMANDE_CLIENT_FILLE offi left join equivalence e
on e.idproduit=offi.PRODUIT and e.idunite=offi.unite
left join as_ingredients ing on ing.id=offi.PRODUIT
union all
select "ID","IDPRODUITS","IDINGREDIENTS",cast (QUANTITE as number(20,2))as quantite,"UNITE","COMPOSE" from AS_RECETTECOMPOSE;



-- 15:47 ajout idclientlib dans vue AS_BONDELIVRAISON_CLIENT_CPL

CREATE OR REPLACE  VIEW AS_BONDELIVRAISON_CLIENT_CPL AS 
  SELECT bl.id, bl.remarque,
v.id AS idvente,
v.designation,
bl.idbc, bl.daty, bl.etat,
m.id AS idmagasin,
m.val AS magasin,
v.IDRESERVATION,
c.nom AS IDCLIENTlib
FROM AS_BONDELIVRAISON_CLIENT bl
LEFT JOIN magasin m ON bl.magasin=m.id
LEFT JOIN vente v ON v.id=bl.idvente
LEFT JOIN client c ON c.ID = bl.IDCLIENT ;


-- 18:15 ajout vue pour bondecommande_fabricationdetails 44[
CREATE OR REPLACE VIEW BONCOMMANDEFABDETAILS AS
SELECT
    fl.IDINGREDIENTS ,
    i.LIBELLEEXTACTE,
    bc.IDBC,
    sum(fl.QTE) qte
FROM FABRICATIONFILLE fl
LEFT JOIN BONDECOMMANDE_CLIENT_FILLE bc ON bc.ID = fl.IDBCFILLE
LEFT JOIN FABRICATION f ON f.ID = fl.IDMERE
JOIN AS_INGREDIENTS i ON fl.IDINGREDIENTS = i.ID
WHERE f.ETAT >= 11
GROUP BY fl.IDINGREDIENTS ,i.LIBELLEEXTACTE,bc.IDBC;


--- 18:42

CREATE OR REPLACE VIEW AS_BC_FILLE_AVEC_PRIX AS
SELECT
    bl.*,
    CAST(ai.PV AS NUMBER(20, 2)) AS pu,
    CAST(ai.TVA AS NUMBER(20, 2)) AS tva
FROM
    AS_BONDELIVRAISON_CLIENT_FILLE bl
LEFT JOIN AS_INGREDIENTS ai
    ON ai.ID = bl.PRODUIT;

--18:57
UPDATE MENUDYNAMIQUE
SET LIBELLE='Creation', ICONE='fa fa-plus', HREF='module.jsp?but=produits/as-ingredients-saisie.jsp', RANG=1, NIVEAU=2, ID_PERE='MNDN00001'
WHERE ID='MNDN000011';

--20:14 vue boncommandeclient_fille details avec qteof, qtefab, qtelivre
CREATE OR REPLACE FORCE VIEW BONDECOMMANDE_CLIENT_FILLE_CPL AS
SELECT
    bcf.ID AS ID,
    bcf.IDBC,
    bcf.IDDEVISE,
    bcf.MONTANT,
    bcf.PRODUIT,
    bcf.PU,
    bcf.QUANTITE,
    bcf.REMISE,
    bcf.TVA,
    bcf.UNITE,

    o.QTE AS QTEOF,

    f.QTE AS QTEFAB,

    SUM(NVL(abcf.QUANTITE, 0)) AS QTELIVRE

FROM BONDECOMMANDE_CLIENT_FILLE bcf

LEFT JOIN OFFILLE o ON o.IDBCFILLE = bcf.ID
LEFT JOIN OFAB o2 ON o2.ID = o.IDMERE AND o2.ETAT >= 11

LEFT JOIN FABRICATIONFILLE f ON f.IDBCFILLE = bcf.ID
LEFT JOIN FABRICATION fab ON fab.ID = f.IDMERE AND fab.ETAT >= 11

LEFT JOIN AS_BONDELIVRAISON_CLIENT_FILLE abcf ON abcf.IDBC_FILLE = bcf.ID
LEFT JOIN AS_BONDELIVRAISON_CLIENT abc ON abc.ID = abcf.NUMBL AND abc.ETAT >= 11

GROUP BY
    bcf.ID,
    bcf.IDBC,
    bcf.IDDEVISE,
    bcf.MONTANT,
    bcf.PRODUIT,
    bcf.PU,
    bcf.QUANTITE,
    bcf.REMISE,
    bcf.TVA,
    bcf.UNITE,
    o.QTE,
    f.QTE;


--mila esorina contraint magasin ao am BONDECOMMANDE_CLIENT

ALTER TABLE BONDECOMMANDE_CLIENT DROP CONSTRAINT FK_MAGASIN;

-- BONDECOMMANDE_OFDETAILS MODIF 22:43

-- CORRECTION COLONNE , AJOUT DATY

CREATE OR REPLACE FORCE VIEW "ASYNCARTISANAT"."BONDECOMMANDE_OFDETAILS" ("IDINGREDIENTS", "LIBELLEEXACTE", "IDBC", "QTE","DATY") AS 
   SELECT off.IDINGREDIENTS,i.LIBELLEEXTACTE,bc.IDBC, sum(off.QTE) qte, o.DATY  FROM 
        OFFILLE off 
    LEFT JOIN BONDECOMMANDE_CLIENT_FILLE bc 
    ON bc.ID = off.IDBCFILLE 
    LEFT JOIN OFAB o 
    ON o.ID = off.IDMERE 
    JOIN AS_INGREDIENTS i
    ON off.IDINGREDIENTS = i.ID 
    WHERE o.ETAT >= 11
    GROUP BY off.IDINGREDIENTS,i.LIBELLEEXTACTE,bc.IDBC,o.DATY ;

-- 20:39 vue bondeLivraison d'un BC 
-- ASYNCARTISANAT.BL_CLIENT_FILLE_BC source

CREATE OR REPLACE FORCE VIEW "ASYNCARTISANAT"."BL_CLIENT_FILLE_BC" ("ID", "IDBC", "PRODUIT", "IDPRODUIT", "QUANTITE", "DATY") AS 
  SELECT
	ABCF.id,
	ABC.IDBC ,
	pl.LIBELLE AS PRODUIT,
	ABCF.PRODUIT AS IDPRODUIT,
	ABCF.QUANTITE ,
	ABC.DATY 
 FROM AS_BONDELIVRAISON_CLIENT_FILLE abcf 
	JOIN BONDECOMMANDE_CLIENT_FILLE bcfc ON BCFC.ID = ABCF.IDBC_FILLE 
	JOIN AS_BONDELIVRAISON_CLIENT abc ON abc.ID = ABCF.NUMBL 
	JOIN AS_INGREDIENTS pl ON pl.ID = ABCF.PRODUIT ;


--- correction menu

DELETE FROM MENUDYNAMIQUE
WHERE ID = 'MNDN0000000123';

UPDATE MENUDYNAMIQUE
SET LIBELLE = 'Bon de livraison',
    ICONE = 'fa fa-truck',
    HREF = NULL,
    RANG = 4,
    NIVEAU = 2,
    ID_PERE = 'MNDN000000001'
WHERE ID = 'MNDN000000012';

UPDATE MENUDYNAMIQUE
SET LIBELLE = 'Saisie',
    ICONE = 'fa fa-plus',
    HREF = 'module.jsp?but=bondelivraison-client/bondelivraison-client-saisie.jsp',
    RANG = 1,
    NIVEAU = 3,
    ID_PERE = 'MNDN000000012'
WHERE ID = 'MNDN0000000121';

UPDATE MENUDYNAMIQUE
SET LIBELLE = 'Liste',
    ICONE = 'fa fa-list',
    HREF = 'module.jsp?but=bondelivraison-client/bondelivraison-client-liste.jsp',
    RANG = 2,
    NIVEAU = 3,
    ID_PERE = 'MNDN000000012'
WHERE ID = 'MNDN0000000122';

UPDATE MENUDYNAMIQUE
SET LIBELLE = 'Facturer livraison',
    ICONE = 'fa fa-list',
    HREF = 'module.jsp?but=vente/bondelivraison-client/facturer-livraison.jsp',
    RANG = 3,
    NIVEAU = 3,
    ID_PERE = 'MNDN000000012'
WHERE ID = 'MNDN00017210082';

UPDATE MENUDYNAMIQUE
SET LIBELLE = 'Facturer livraison',
    ICONE = 'fa fa-list', 
    HREF = 'module.jsp?but=bondelivraison/facturer-livraison.jsp',
    RANG = 3,
    NIVEAU = 3,
    ID_PERE = 'MNDN000000' 
WHERE ID = 'MNDNT07080001';


-- enlever contrainte magasin

ALTER TABLE AS_BONDELIVRAISON_CLIENT DROP CONSTRAINT SYS_C0028608;


--- vue BONDECOMMANDE_CLIENT_FILLE_CPL
CREATE OR REPLACE VIEW BONDECOMMANDE_CLIENT_FILLE_CPL AS
SELECT
    '-' AS ID,
    bcf.IDBC,
    bcf.IDDEVISE,
    AVG(bcf.MONTANT) AS montant,
    bcf.PRODUIT,
    AVG(bcf.PU) AS pu,
    AVG(bcf.QUANTITE) AS quantite,
    AVG(bcf.REMISE) AS remise,
    AVG(bcf.TVA) AS tva,
    MAX(bcf.UNITE) AS unite,

    NVL(SUM(o.QTE), 0) AS QTEOF,
    NVL(SUM(bcf.QUANTITE) - SUM(o.QTE), 0) AS QTEOFRESTANTE,

    NVL(SUM(f.QTE), 0) AS QTEFAB,
    NVL(SUM(bcf.QUANTITE) - SUM(f.QTE), 0) AS QTEFABRESTANTE,

    SUM(NVL(abcf.QUANTITE, 0)) AS QTELIVRE,
    NVL(AVG(bcf.QUANTITE) - SUM(NVL(abcf.QUANTITE, 0)), 0) AS QTENONLIVRE,

    ing.LIBELLE AS libelleProduit

FROM BONDECOMMANDE_CLIENT_FILLE bcf

LEFT JOIN OFFILLE o ON o.IDBCFILLE = bcf.ID
LEFT JOIN OFAB o2 ON o2.ID = o.IDMERE AND o2.ETAT >= 11

LEFT JOIN FABRICATIONFILLE f ON f.IDBCFILLE = bcf.ID
LEFT JOIN FABRICATION fab ON fab.ID = f.IDMERE AND fab.ETAT >= 11

LEFT JOIN AS_BONDELIVRAISON_CLIENT_FILLE abcf ON abcf.IDBC_FILLE = bcf.ID
LEFT JOIN AS_BONDELIVRAISON_CLIENT abc ON abc.ID = abcf.NUMBL AND abc.ETAT >= 11

LEFT JOIN AS_INGREDIENTS ing ON ing.ID = bcf.PRODUIT

GROUP BY
    bcf.IDBC,
    bcf.IDDEVISE,
    bcf.PRODUIT,
    ing.LIBELLE;


--BONDECOMMANDE_CLIENT_FILLE_CPL

CREATE OR REPLACE VIEW BONDECOMMANDE_CLIENT_FILLE_CPL AS
SELECT
    '-' AS ID,
    bcf.IDBC,
    bcf.IDDEVISE,
    AVG(bcf.MONTANT) AS montant,
    bcf.PRODUIT,
    AVG(bcf.PU) AS pu,
    AVG(bcf.QUANTITE) AS quantite,
    AVG(bcf.REMISE) AS remise,
    AVG(bcf.TVA) AS tva,
    MAX(bcf.UNITE) AS unite,

    NVL(SUM(o.QTE), 0) AS QTEOF,
    NVL(SUM(bcf.QUANTITE) - SUM(o.QTE), 0) AS QTEOFRESTANTE,

    NVL(SUM(f.QTE), 0) AS QTEFAB,
    NVL(SUM(bcf.QUANTITE) - SUM(f.QTE), 0) AS QTEFABRESTANTE,

    SUM(NVL(abcf.QUANTITE, 0)) AS QTELIVRE,
    NVL(AVG(bcf.QUANTITE) - SUM(NVL(abcf.QUANTITE, 0)), 0) AS QTENONLIVRE,

    ing.LIBELLE AS libelleProduit

FROM BONDECOMMANDE_CLIENT_FILLE bcf

LEFT JOIN OFFILLE o ON o.IDBCFILLE = bcf.ID
LEFT JOIN OFAB o2 ON o2.ID = o.IDMERE AND o2.ETAT >= 11

LEFT JOIN FABRICATIONFILLE f ON f.IDBCFILLE = bcf.ID
LEFT JOIN FABRICATION fab ON fab.ID = f.IDMERE AND fab.ETAT >= 11

LEFT JOIN AS_BONDELIVRAISON_CLIENT_FILLE abcf ON abcf.IDBC_FILLE = bcf.ID
LEFT JOIN AS_BONDELIVRAISON_CLIENT abc ON abc.ID = abcf.NUMBL AND abc.ETAT >= 11

LEFT JOIN AS_INGREDIENTS ing ON ing.ID = bcf.PRODUIT

GROUP BY
    bcf.IDBC,
    bcf.IDDEVISE,
    bcf.PRODUIT,
    ing.LIBELLE;


--21:51

CREATE OR REPLACE FORCE VIEW BONCOMMANDEFABDETAILS AS
  SELECT
	fl.IDINGREDIENTS ,
	i.LIBELLEEXTACTE,
	bc.ID,
	sum(fl.QTE) qte,
	fl.IDMERE AS IDFABRICATION
FROM FABRICATIONFILLE fl
LEFT JOIN BONDECOMMANDE_CLIENT_FILLE bcf ON bcf.ID = fl.IDBCFILLE
LEFT JOIN BONDECOMMANDE_CLIENT bc ON bc.ID = bcf.IDBC
LEFT JOIN FABRICATION f
ON f.ID = fl.IDMERE
JOIN AS_INGREDIENTS i
ON fl.IDINGREDIENTS = i.ID
WHERE f.ETAT >= 11
GROUP BY fl.IDINGREDIENTS ,i.LIBELLEEXTACTE,bc.ID, fl.IDMERE;

--

-- Vue : Quantité fabriquée groupée par IDBCFILLE
CREATE OR REPLACE VIEW fabrGroupByIdbc AS
SELECT 
    f.IDBCFILLE,
    SUM(f.QTE) AS qte
FROM FABRICATIONFILLE f
LEFT JOIN FABRICATION m ON m.ID = f.IDMERE
WHERE m.ETAT >= 11
GROUP BY f.IDBCFILLE;

-- Vue : Quantité d'OF groupée par IDBCFILLE
CREATE OR REPLACE VIEW OfGroupByIdbc AS
SELECT 
    f.IDBCFILLE,
    SUM(f.QTE) AS qte
FROM OFFILLE f
LEFT JOIN OFAB m ON m.ID = f.IDMERE
WHERE m.ETAT >= 11
GROUP BY f.IDBCFILLE;

-- Vue : Quantité livrée groupée par IDBC_FILLE
CREATE OR REPLACE VIEW BLGroupByIdbc AS
SELECT 
    f.IDBC_FILLE,
    SUM(f.QUANTITE) AS quantite
FROM AS_BONDELIVRAISON_CLIENT_FILLE f
LEFT JOIN AS_BONDELIVRAISON_CLIENT m ON m.ID = f.NUMBL
WHERE m.ETAT >= 11
GROUP BY f.IDBC_FILLE;

-- Vue : Données complètes enrichies sur les lignes de bons de commande client
CREATE OR REPLACE VIEW BONDECOMMANDE_CLIENT_FILLE_CPL AS
SELECT
    '-' AS ID,
    bcf.IDBC,
    bcf.IDDEVISE,
    AVG(bcf.MONTANT) AS montant,
    bcf.PRODUIT,
    AVG(bcf.PU) AS pu,
    AVG(bcf.QUANTITE) AS quantite,
    AVG(bcf.REMISE) AS remise,
    AVG(bcf.TVA) AS tva,
    MAX(bcf.UNITE) AS unite,

    NVL(AVG(o.QTE), 0) AS QTEOF,
    NVL(SUM(bcf.QUANTITE) - NVL(AVG(o.QTE), 0), 0) AS QTEOFRESTANTE,

    NVL(AVG(f.QTE), 0) AS QTEFAB,
    NVL(SUM(bcf.QUANTITE) - NVL(AVG(f.QTE), 0), 0) AS QTEFABRESTANTE,

    AVG(NVL(abcf.QUANTITE, 0)) AS QTELIVRE,
    NVL(AVG(bcf.QUANTITE) - AVG(NVL(abcf.QUANTITE, 0)), 0) AS QTENONLIVRE,

    ing.LIBELLE AS libelleProduit

FROM BONDECOMMANDE_CLIENT_FILLE bcf
LEFT JOIN OfGroupByIdbc o ON o.IDBCFILLE = bcf.ID
LEFT JOIN fabrGroupByIdbc f ON f.IDBCFILLE = bcf.ID
LEFT JOIN BLGroupByIdbc abcf ON abcf.IDBC_FILLE = bcf.ID
LEFT JOIN AS_INGREDIENTS ing ON ing.ID = bcf.PRODUIT

GROUP BY
    bcf.IDBC,
    bcf.ID,
    bcf.IDDEVISE,
    bcf.PRODUIT,
    ing.LIBELLE;

-- Requête d’exploration brute (debug ou contrôle)
SELECT 
    bcf.*
FROM BONDECOMMANDE_CLIENT_FILLE bcf
LEFT JOIN OFFILLE o ON o.IDBCFILLE = bcf.ID
LEFT JOIN OFAB o2 ON o2.ID = o.IDMERE AND o2.ETAT >= 11
LEFT JOIN FABRICATIONFILLE f ON f.IDBCFILLE = bcf.ID
LEFT JOIN FABRICATION fab ON fab.ID = f.IDMERE AND fab.ETAT >= 11
LEFT JOIN AS_BONDELIVRAISON_CLIENT_FILLE abcf ON abcf.IDBC_FILLE = bcf.ID
LEFT JOIN AS_BONDELIVRAISON_CLIENT abc ON abc.ID = abcf.NUMBL AND abc.ETAT >= 11
LEFT JOIN AS_INGREDIENTS ing ON ing.ID = bcf.PRODUIT;

--22:41
DELETE FROM FACTUREFOURNISSEURFILLE
WHERE idfacturefournisseur='FCF000322';

DELETE FROM FACTUREFOURNISSEUR
WHERE ID='FCF000322';

DELETE FROM FACTUREFOURNISSEURFILLE
WHERE idfacturefournisseur='FFD000362';

DELETE FROM FACTUREFOURNISSEUR
WHERE ID='FCF000354';

DELETE FROM FACTUREFOURNISSEURFILLE
WHERE idfacturefournisseur='FCF000355';

DELETE FROM FACTUREFOURNISSEUR
WHERE ID='FCF000355';

--22:55
UPDATE ASYNCARTISANAT.AS_INGREDIENTS
SET COMPTE_VENTE = '710011', COMPTE_ACHAT = '610011'
WHERE ID IN (
  'IG000001',
  'IG000002',
  'IG000003',
  'IG000004',
  'IG000005',
  'IG000006',
  'IG000007',
  'IG0000025',
  'IG0000026',
  'IG0000027',
  'IG0000028',
  'IG0000029'
);