ALTER TABLE AS_INGREDIENTS
ADD estchangeable INT;

UPDATE AS_INGREDIENTS SET estchangeable = 0 WHERE ID='ING00V00004'; -- KIP COCO
UPDATE AS_INGREDIENTS SET estchangeable = 1 WHERE ID='ING000T0190'; --tchido
UPDATE AS_INGREDIENTS SET estchangeable = 1 WHERE ID='ING000T0125'; --tchido



