CREATE OR REPLACE  VIEW UPDATEVENTE (ID, DESIGNATION, IDMAGASIN, DATY, REMARQUE, ETAT, IDORIGINE, IDCLIENT, IDCLIENTLIB, IDDEVISE, IDRESERVATION, DATYPREVU,ECHEANCEFACTURE,ESTPREVU) AS 
  SELECT
	v.ID,
	v.DESIGNATION,
	v.IDMAGASIN,
	v.DATY,
	v.REMARQUE,
	v.ETAT,
	v.IDORIGINE,
	v.IDCLIENT,
	c.NOM AS idClientLib,
	v2.IDDEVISE,
	v.IDRESERVATION,
	v.DATYPREVU ,
	v.ECHEANCEFACTURE,
	v.ESTPREVU
FROM VENTE v
JOIN CLIENT c ON c.ID = v.IDCLIENT
JOIN VENTEMONTANT v2 ON v2.ID = v.ID;