ALTER TABLE AVOIRFC MODIFY IDMAGASIN VARCHAR2(255) NULL;

CREATE TABLE typeavoir(
	id varchar2(100) PRIMARY KEY NOT NULL,
	val varchar2(100),
	desce varchar2(100)
);
CREATE SEQUENCE seqtypeavoir INCREMENT BY 1 MINVALUE 1 MAXVALUE 999999999999 NOCYCLE CACHE 20 NOORDER ;
CREATE OR REPLACE FUNCTION getseqtypeavoir
   RETURN NUMBER
IS
   retour   NUMBER;
BEGIN
   SELECT seqtypeavoir.NEXTVAL INTO retour FROM DUAL;

   RETURN retour;
END;
INSERT INTO TYPEAVOIR (ID, VAL, DESCE) VALUES('TYA0001', 'Ristourne', 'Ristourne');
INSERT INTO TYPEAVOIR (ID, VAL, DESCE) VALUES('TYA0002', 'Avoir', 'Avoir');
ALTER TABLE avoirfc ADD idtypeavoir VARCHAR2(255);
ALTER TABLE avoirfc ADD CONSTRAINT fk_avoirfc_typeavoir FOREIGN KEY (idtypeavoir) REFERENCES typeavoir(id);

-- SOCOBISPROD1509.AVOIRFCLIB source

CREATE OR REPLACE VIEW AVOIRFCLIB (ID, DESIGNATION, IDMAGASIN, IDMAGASINLIB, DATY, REMARQUE, ETAT, IDORIGINE, IDCLIENT, COMPTE, COMPTEAUXILIAIRE, IDVENTE, IDVENTELIB, IDMOTIF, IDMOTIFLIB, IDCATEGORIE, IDCATEGORIELIB, IDDEVISE, TAUXDECHANGE, MONTANTHT, MONTANTTVA, MONTANTTTC, MONTANTHTAR, MONTANTTVAAR, MONTANTTTCAR, IDRESERVATION) AS 
  SELECT a.ID,
       a.DESIGNATION,
       a.IDMAGASIN,
       m.VAL         AS IDMAGASINLIB,
       a.DATY,
       a.REMARQUE,
       a.ETAT,
       a.IDORIGINE,
       a.IDCLIENT,
       t.COMPTE,
       t.compteauxiliaire,
       a.IDVENTE,
       v.DESIGNATION AS IDVENTELIB,
       a.IDMOTIF,
       ma.VAL        AS IDMOTIFLIB,
       a.IDCATEGORIE,
       c.VAL         AS IDCATEGORIELIB,
       ag.IDDEVISE,
       ag.TAUXDECHANGE,
       ag.MONTANTHT,
       ag.MONTANTTVA,
       ag.MONTANTTTC,
       ag.MONTANTHTAR,
       ag.MONTANTTVAAR,
       ag.MONTANTTTCAR,
       v.IDRESERVATION
FROM AVOIRFC a
         LEFT JOIN MAGASIN2 m ON m.id = a.IDMAGASIN
         LEFT JOIN VENTE v ON v.id = a.IDVENTE
         LEFT JOIN MOTIFAVOIRFC ma ON ma.id = a.IDMOTIF
         LEFT JOIN CATEGORIEAVOIRFC c ON c.id = a.IDCATEGORIE
         JOIN AVOIRFCFILLE_GRP ag ON ag.idavoirfc = a.id
         LEFT JOIN TIERS T ON T.ID = A.IDCLIENT;
        
  -- SOCOBISPROD1509.AVOIRFCLIB_CPL source

CREATE OR REPLACE  VIEW AVOIRFCLIB_CPL (ID, DESIGNATION, IDMAGASIN, IDMAGASINLIB, DATY, REMARQUE, ETAT, IDORIGINE, IDCLIENT, COMPTE, IDVENTE, IDVENTELIB, IDMOTIF, IDMOTIFLIB, IDCATEGORIE, IDCATEGORIELIB, IDDEVISE, TAUXDECHANGE, MONTANTHT, MONTANTTVA, MONTANTTTC, MONTANTHTAR, MONTANTTVAAR, MONTANTTTCAR, MONTANTPAYE, MONTANTPAYEAR, RESTEAPAYER, RESTEAPAYERAR,idtypeavoirlib) AS 
  SELECT AL.ID,
       AL.DESIGNATION,
       AL.IDMAGASIN,
       AL.IDMAGASINLIB,
       AL.DATY,
       AL.REMARQUE,
       AL.ETAT,
       AL.IDORIGINE,
       AL.IDCLIENT,
       AL.COMPTE,
       AL.IDVENTE,
       AL.IDVENTELIB,
       AL.IDMOTIF,
       AL.IDMOTIFLIB,
       AL.IDCATEGORIE,
       AL.IDCATEGORIELIB,
       AL.IDDEVISE,
       AL.TAUXDECHANGE,
       AL.MONTANTHT,
       AL.MONTANTTVA,
       AL.MONTANTTTC,
       AL.MONTANTHTAR,
       AL.MONTANTTVAAR,
       AL.MONTANTTTCAR,
       M.DEBIT as MONTANTPAYE,
       nvl(M.DEBIT, 0)*nvl(AL.TAUXDECHANGE, 0) as MONTANTPAYEAR,
       AL.MONTANTTTC - nvl(M.DEBIT, 0) as RESTEAPAYER,
       AL.MONTANTTTCAR - (nvl(M.DEBIT,0)*nvl(AL.TAUXDECHANGE, 0)) as RESTEAPAYERAR,
       AL.idtypeavoirlib
from AVOIRFCLIB AL
LEFT JOIN MOUVEMENTCAISSEGROUPEFACTURE M on AL.ID = M.IDORIGINE;


CREATE OR REPLACE  VIEW AVOIRFCFILLELIB (ID, IDAVOIRFC, IDPRODUIT, IDORIGINE, QTE, PU, REMISE, TVA, PUACHAT, PUVENTE, IDDEVISE, TAUXDECHANGE, DESIGNATION, IDVENTEDETAILS, IDPRODUITLIB) AS 
SELECT
	AF.ID,
	AF.IDAVOIRFC,
	AF.IDPRODUIT,
	AF.IDORIGINE,
	AF.QTE,
	AF.PU,
	AF.REMISE,
	AF.TVA,
	AF.PUACHAT,
	AF.PUVENTE,
	AF.IDDEVISE,
	AF.TAUXDECHANGE,
	AF.DESIGNATION,
	AF.IDVENTEDETAILS,
	P.libelle AS IDPRODUITLIB
FROM
	AVOIRFCFILLE AF
LEFT JOIN as_ingredients P ON
	P.id = AF.IDPRODUIT;


   ALTER TABLE vente ADD echeanceFacture number(38,2); 


CREATE OR REPLACE  VIEW INSERTION_VENTE (ID, DESIGNATION, IDMAGASIN, DATY, REMARQUE, ETAT, IDORIGINE, IDCLIENT, IDDEVISE, ESTPREVU, DATYPREVU, IDRESERVATION,echeancefacture) AS 
  SELECT
	v.ID,
	v.DESIGNATION,
	v.IDMAGASIN,
	v.DATY,
	v.REMARQUE,
	v.ETAT,
	v.IDORIGINE,
	v.IDCLIENT,
	CAST(' ' AS varchar(100)) AS iddevise,
	v.ESTPREVU,
	v.DATYPREVU,
	v.IDRESERVATION,
	v.echeancefacture
FROM VENTE v;

-- SOCOBISPROD1509.BONDECOMMANDE_CLIENT_CPL source
ALTER TABLE BONDECOMMANDE_CLIENT ADD idproforma varchar2(255);
ALTER TABLE BONDECOMMANDE_CLIENT_FILLE ADD designation varchar2(255);
CREATE OR REPLACE  VIEW BONDECOMMANDE_CLIENT_CPL (ID, DATY, ETAT, REMARQUE, DESIGNATION, MODEPAIEMENT, MODEPAIEMENTLIB, IDCLIENT, IDCLIENTLIB, REFERENCE, IDMAGASINLIB, ETATLIB,IDPROFORMA) AS 
  SELECT
bc.ID,
bc.DATY,
bc.ETAT,
bc.REMARQUE,
bc.DESIGNATION,
bc.MODEPAIEMENT,
m.VAL AS MODEPAIEMENTLIB,
bc.IDCLIENT,
c.NOM AS IDCLIENTLIB,
bc.REFERENCE,
m2.VAL AS IDMAGASINLIB,
CASE
    WHEN bc.ETAT = 0 THEN '<span style=color: green;>ANNULEE</span>'
    WHEN bc.ETAT = 1 THEN '<span style=color: green;>CREE</span>'
    WHEN bc.ETAT = 11 THEN '<span style=color: green;>VALIDEE</span>'
END AS ETATLIB,
bc.IDPROFORMA
FROM BONDECOMMANDE_CLIENT bc
LEFT JOIN CLIENT c ON c.id = bc.IDCLIENT
LEFT JOIN MODEPAIEMENT m ON m.id = bc.MODEPAIEMENT
LEFT JOIN MAGASIN2 m2 ON m2.id = bc.IDMAGASIN
;



CREATE OR REPLACE  VIEW VENTE_CPL_BC_VISEE (ID, DESIGNATION, IDMAGASIN, IDMAGASINLIB, DATY, REMARQUE, ETAT, ETATLIB, MONTANTTOTAL, IDDEVISE, IDCLIENT, CLIENTLIB, MONTANTTVA, MONTANTTTC, MONTANTTTCAR, MONTANTPAYE, MONTANTRESTE, AVOIR, TAUXDECHANGE, MONTANTREVIENT, MARGEBRUTE, IDRESERVATION, IDORIGINE) AS 
  SELECT v.ID,
       v.DESIGNATION,
       v.IDMAGASIN,
       m.VAL AS IDMAGASINLIB,
       v.DATY,
       v.REMARQUE,
       v.ETAT,
       CASE
           WHEN v.ETAT = 1 THEN 'CREE'
           WHEN v.ETAT = 11 THEN 'VISEE'
           WHEN v.ETAT = 0 THEN 'ANNULEE'
           END
             AS ETATLIB,
       v2.MONTANTTOTAL,
       v2.IDDEVISE,
       v.IDCLIENT,
       c.NOM AS CLIENTLIB,
       cast(V2.MONTANTTVA as number(30,2)) as MONTANTTVA,
       cast(V2.MONTANTTTC as number(30,2)) as montantttc,
       cast(V2.MONTANTTTCAR as number(30,2)) as MONTANTTTCAR,
       cast(nvl(mv.credit,0)-nvl(ACG.MONTANTPAYE, 0) AS NUMBER(30,2)) AS montantpaye,
       cast(V2.MONTANTTTC-nvl(mv.credit,0)-nvl(ACG.resteapayer_avr, 0) AS NUMBER(30,2)) AS montantreste,
       nvl(ACG.MONTANTTTC_avr, 0)  as avoir,
       v2.tauxDeChange AS tauxDeChange,v2.MONTANTREVIENT,cast((V2.MONTANTTTCAR-v2.MONTANTREVIENT) as number(20,2))  as margeBrute,
       v.IDRESERVATION,
       v.idorigine as IDORIGINE
FROM VENTE v
         LEFT JOIN CLIENT c ON c.ID = v.IDCLIENT
         LEFT JOIN MAGASIN m ON m.ID = v.IDMAGASIN
         JOIN VENTEMONTANT v2 ON v2.ID = v.ID
         LEFT JOIN mouvementcaisseGroupeFacture mv ON v.id=mv.IDORIGINE
         LEFT JOIN AVOIRFCLIB_CPL_GRP ACG on ACG.IDVENTE = v.ID
         left join AS_BONDELIVRAISON_CLIENT asbl on asbl.ID = v.IDORIGINE
where v.ETAT = 11;


ALTER TABLE VENTE_DETAILS ADD idbcfille varchar2(100);
CREATE OR REPLACE VIEW VENTE_DETAILS_SAISIE (ID, IDVENTE, IDPRODUIT, DESIGNATION, IDORIGINE, QTE, PU, REMISE, TVA, PUACHAT, PUVENTE, IDDEVISE, TAUXDECHANGE, COMPTE,IDBCFILLE) AS 
  SELECT 
         id,
         IDVENTE ,
         IDPRODUIT ,
         DESIGNATION ,
         IDORIGINE ,
         qte,
         pu,
         REMISE ,
         TVA ,
         PUACHAT ,
         PUVENTE ,
         IDDEVISE ,
         TAUXDECHANGE ,
         compte,
         vd.idbcfille
         FROM VENTE_DETAILS vd 
;
CREATE VIEW vente_details_qte_grp as
SELECT idbcfille AS idbcfille,sum(qte) AS qte FROM VENTE_DETAILS vd GROUP BY idbcfille;


CREATE OR REPLACE  VIEW BC_CLIENT_FILLE_CPL_LIB (ID, PRODUIT, IDBC, QUANTITE, PU, MONTANT, TVA, REMISE, IDDEVISE, UNITE, PRODUITLIB,compte,qtereste) AS 
 SELECT
	bcf.ID,
	bcf.PRODUIT,
	bcf.IDBC,
	bcf.QUANTITE,
	bcf.PU,
	bcf.MONTANT,
	bcf.TVA,
	bcf.REMISE,
	bcf.IDDEVISE,
	bcf.UNITE,
	i.LIBELLE AS PRODUITlib,
	i.compte_vente AS compte,
	NVL(bcf.quantite, 0) - NVL(vdbc.qte, 0) AS qtereste
FROM
bondecommande_client_fille bcf
JOIN as_ingredients i ON i.id = bcf.PRODUIT
LEFT JOIN vente_details_qte_grp vdbc ON bcf.id = vdbc.idbcfille;