
CREATE OR REPLACE  VIEW VENTE_DETAILS_CPL_2 (ID, IDVENTE, IDVENTELIB, IDPRODUIT, IDPRODUITLIB, IDORIGINE, QTE, PU, PUTOTAL, PUTOTALACHAT, PUREVIENT, IDCATEGORIE, IDCATEGORIELIB, DATY, IDMAGASIN, IDMAGASINLIB, IDPOINT, IDPOINTLIB, IDDEVISE, IDDEVISELIB, IDRESERVATION,IDBCFILLE) AS 
  SELECT vd.ID,
       vd.IDVENTE,
       v.DESIGNATION          AS IDVENTELIB,
       vd.IDPRODUIT,
       p.LIBELLE                  AS IDPRODUITLIB,
       vd.IDORIGINE,
       vd.QTE,
       nvl(vd.PU, 0)          AS PU,
       CAST(nvl(vd.PU * vd.QTE*(1-nvl(vd.REMISE,0)/100), 0) +nvl(vd.PU * vd.QTE*(1-nvl(vd.REMISE,0)/100) *(vd.TVA/100), 0) AS number(30,2)) AS puTotal,
       CAST(nvl(vd.PUACHAT * vd.QTE, 0) AS number(30,2)) AS puTotalAchat,
       CAST(nvl(vd.PU * vd.QTE, 0) - nvl(vd.PUACHAT * vd.QTE, 0) AS number(30,2)) AS puRevient,
       c.ID  AS IDCATEGORIE,
       c.VAL AS IDCATEGORIELIB,
       v.DATY AS daty,
       m.ID AS IDMAGASIN,
       m.VAL AS IDMAGASINLIB,
       p1.ID AS IDPOINT,
       p1.VAL AS IDPOINTLIB,
       vd.IDDEVISE,
       vd.IDDEVISE AS IDDEVISELIB,
       v.IDRESERVATION,
       vd.IDBCFILLE
FROM VENTE_DETAILS vd
         LEFT JOIN VENTE v ON v.ID = vd.IDVENTE
         LEFT JOIN MAGASIN m ON m.ID = v.IDMAGASIN
         LEFT JOIN AS_INGREDIENTS p ON p.ID = vd.IDPRODUIT
         LEFT JOIN POINT p1 ON p1.ID = m.IDPOINT
         LEFT JOIN CATEGORIE c  ON p.CATEGORIEINGREDIENT  = c.ID;


CREATE OR REPLACE  VIEW VENTE_DETAILS_CPL_2_VISEE (ID, IDVENTE, IDVENTELIB, IDPRODUIT, IDPRODUITLIB, IDORIGINE, QTE, PU, PUTOTAL, PUTOTALACHAT, PUREVIENT, IDCATEGORIE, IDCATEGORIELIB, DATY, IDMAGASIN, IDMAGASINLIB, IDPOINT, IDPOINTLIB, IDDEVISE, IDDEVISELIB, IDRESERVATION,IDBCFILLE) AS 
  select vd.ID,vd.IDVENTE,vd.IDVENTELIB,vd.IDPRODUIT,vd.IDPRODUITLIB,vd.IDORIGINE,vd.QTE,vd.PU,vd.PUTOTAL,vd.PUTOTALACHAT,vd.PUREVIENT,vd.IDCATEGORIE,vd.IDCATEGORIELIB,vd.DATY,vd.IDMAGASIN,vd.IDMAGASINLIB,vd.IDPOINT,vd.IDPOINTLIB,vd.IDDEVISE,vd.IDDEVISELIB,vd.IDRESERVATION,vd.idbcfille from VENTE_DETAILS_CPL_2 vd
         LEFT JOIN VENTE v ON v.ID = vd.IDVENTE
WHERE v.ETAT >= 11;

CREATE OR REPLACE  VIEW VENTE_DETAILS_QTE_GRP (IDBCFILLE, QTE) AS 
  SELECT idbcfille AS idbcfille,sum(qte) AS qte FROM VENTE_DETAILS_CPL_2_VISEE vd GROUP BY idbcfille ;
  
 
