-- rectif etat lib
CREATE OR REPLACE FORCE VIEW "PROFORMA_CPL" ("ID", "DESIGNATION", "IDMAGASIN", "IDMAGASINLIB", "DATY", "REMARQUE", "ETAT", "ETATLIB", "IDDEVISE", "IDCLIENT", "IDCLIENTLIB", "ADRESSE", "CONTACT", "MONTANT", "MONTANTTOTAL", "MONTANTREMISE", "MONTANTTVA", "MONTANTTTC", "MONTANTTTCAR", "MONTANTPAYE", "MONTANTRESTE", "AVOIR", "TAUXDECHANGE", "MONTANTREVIENT", "MARGEBRUTE", "IDRESERVATION", "IDORIGINE", "REMISE") AS
SELECT v.ID,
       v.DESIGNATION,
       v.IDMAGASIN,
       m.VAL AS IDMAGASINLIB,
       v.DATY,
       v.REMARQUE,
       v.ETAT,
       CASE
           WHEN v.ETAT = 1 THEN 'CRÉÉE'
           WHEN v.ETAT = 11 THEN 'VISÉE'
           WHEN v.ETAT = 0 THEN 'ANNULÉE'
           END
             AS ETATLIB,
       v2.IDDEVISE,
       v.IDCLIENT,
       c.NOM AS IDCLIENTLIB,
       c.ADRESSE,
       c.TELEPHONE AS CONTACT,
       cast(V2.montant as number(30,2)) as montant,
       v2.MONTANTTOTAL,
       cast(V2.montantremise as number(30,2)) as MONTANTREMISE,
       cast(V2.MONTANTTVA as number(30,2)) as MONTANTTVA,
       cast(V2.MONTANTTTC as number(30,2)) as montantttc,
       cast(V2.MONTANTTTCAR as number(30,2)) as MONTANTTTCAR,
       cast(nvl(mv.credit,0)-nvl(ACG.MONTANTPAYE, 0) AS NUMBER(30,2)) AS montantpaye,
       cast(V2.MONTANTTTC-nvl(mv.credit,0)-nvl(ACG.resteapayer_avr, 0) AS NUMBER(30,2)) AS montantreste,
       nvl(ACG.MONTANTTTC_avr, 0)  as avoir,
       v2.tauxDeChange AS tauxDeChange,v2.MONTANTREVIENT,cast((V2.MONTANTTTCAR-v2.MONTANTREVIENT) as number(20,2))  as margeBrute,
       v.IDRESERVATION,
       v.IDORIGINE,
       v.remise
FROM PROFORMA v
         LEFT JOIN CLIENT c ON c.ID = v.IDCLIENT
         LEFT JOIN MAGASIN2 m ON m.ID = v.IDMAGASIN
         JOIN PROFORMAMONTANT2 v2 ON v2.ID = v.ID
         LEFT JOIN mouvementcaisseGroupeFacture mv ON v.id=mv.IDORIGINE
         LEFT JOIN AVOIRFCLIB_CPL_GRP ACG on ACG.IDVENTE = v.ID;
-- etat lib
CREATE OR REPLACE FORCE VIEW "BONDECOMMANDE_CLIENT_CPL" ("ID", "DATY", "ETAT", "REMARQUE", "DESIGNATION", "MODEPAIEMENT", "MODEPAIEMENTLIB", "IDCLIENT", "IDCLIENTLIB", "REFERENCE", "IDMAGASINLIB", "ETATLIB", "IDPROFORMA") AS
SELECT
    bc.ID,
    bc.DATY,
    bc.ETAT,
    bc.REMARQUE,
    bc.DESIGNATION,
    bc.MODEPAIEMENT,
    m.VAL AS MODEPAIEMENTLIB,
    bc.IDCLIENT,
    c.NOM AS IDCLIENTLIB,
    bc.REFERENCE,
    m2.VAL AS IDMAGASINLIB,
    CASE
        WHEN bc.ETAT = 0 THEN '<span style=color: green;>ANNULÉE</span>'
        WHEN bc.ETAT = 1 THEN '<span style=color: green;>CRÉÉE</span>'
        WHEN bc.ETAT = 11 THEN '<span style=color: green;>VALIDÉE</span>'
        END AS ETATLIB,
    bc.IDPROFORMA
FROM BONDECOMMANDE_CLIENT bc
         LEFT JOIN CLIENT c ON c.id = bc.IDCLIENT
         LEFT JOIN MODEPAIEMENT m ON m.id = bc.MODEPAIEMENT
         LEFT JOIN MAGASIN2 m2 ON m2.id = bc.IDMAGASIN
;
-- ETAT LIB BC MERE
CREATE OR REPLACE FORCE VIEW "AS_BONDECOMMANDE_MERECPL" ("ID", "DATY", "ETAT", "REMARQUE", "DESIGNATION", "MODEPAIEMENT", "FOURNISSEUR", "REFERENCE", "MODEPAIEMENTLIB", "FOURNISSEURLIB", "MONTANTTVA", "MONTANTHT", "MONTANTTTC", "MONTANTTTCARIARY", "IDDEVISELIB", "IDDEVISE","ETATLIB") AS
SELECT
    ab.ID,
    ab.DATY,
    ab.ETAT,
    ab.REMARQUE,
    ab.DESIGNATION,
    ab.MODEPAIEMENT,
    ab.FOURNISSEUR,
    ab.REFERENCE,
    mp.VAL AS MODEPAIEMENTLIB,
    F.NOM AS FOURNISSEURLIB,
    abf.montantTVA,
    abf.montantHT,
    CAST(nvl((abf.montantHT + abf.montantTVA),0) AS NUMBER(30,2)) AS montantTTC ,
    CAST(nvl((abf.montantHT + abf.montantTVA) * abf.TAUXDECHANGE,0) AS NUMBER(30,2)) AS montantTTCAriary,
    d.val AS idDeviselib,
    d.id AS IDDEVISE,
    CASE
        WHEN ab.ETAT = 0
            THEN 'ANNULÉ'
        WHEN ab.ETAT = 1
            THEN 'CRÉÉ'
        WHEN ab.ETAT = 11
            THEN 'VISÉ'
        END AS etatlib
from  AS_BONDECOMMANDE AB
          left join MODEPAIEMENT mp on AB.MODEPAIEMENT = mp.id
          left join FOURNISSEUR F on AB.FOURNISSEUR = F.id
          LEFT JOIN AS_BONDECOMMANDEFILLE_CPL abf ON abf.IDBC = ab.ID
          LEFT JOIN DEVISE d ON d.id = ab.IDDEVISE;

UPDATE MENUDYNAMIQUE
SET LIBELLE='Details par prix unitaire' WHERE ID='MNDN0002706171';

-- MENU ET ORDRE
UPDATE MENUDYNAMIQUE
SET RANG=1
WHERE ID='ELM00T3004001';
UPDATE MENUDYNAMIQUE
SET RANG=2
WHERE ID='MNDN000000001';

UPDATE MENUDYNAMIQUE
SET LIBELLE='Dépense en matière première'
WHERE ID='MENDYN1756300444397-505';
UPDATE MENUDYNAMIQUE
SET LIBELLE='Stock de produits fini'
WHERE ID='MENDYN1756371601724688';

INSERT INTO MENUDYNAMIQUE
(ID, LIBELLE, ICONE, HREF, RANG, NIVEAU, ID_PERE)
VALUES('MDO00000561234', 'Facture', 'fa fa-list-alt', '#', 2, 2, 'MNDN000000001');
INSERT INTO MENUDYNAMIQUE
(ID, LIBELLE, ICONE, HREF, RANG, NIVEAU, ID_PERE)
VALUES('MDO000005612345', 'Ristourne', 'fa fa-book', '#', 8, 2, 'MNDN000000001');
UPDATE MENUDYNAMIQUE
SET NIVEAU=3, ID_PERE='MDO00000561234'
WHERE ID='MNDN000000006';
UPDATE MENUDYNAMIQUE
SET NIVEAU=3, ID_PERE='MDO00000561234'
WHERE ID='MNDN000000007';
UPDATE MENUDYNAMIQUE
SET RANG=4
WHERE ID='MNDN0001109001';
UPDATE MENUDYNAMIQUE
SET RANG=1
WHERE ID='ELM01';
UPDATE MENUDYNAMIQUE
SET RANG=2
WHERE ID='MNDN000000010';
UPDATE MENUDYNAMIQUE
SET RANG=5
WHERE ID='MNDN000000012';
UPDATE MENUDYNAMIQUE
SET RANG=6
WHERE ID='MNDN00000000107';
UPDATE MENUDYNAMIQUE
SET RANG=10
WHERE ID='MNDN0005050001';
UPDATE MENUDYNAMIQUE
SET RANG=7
WHERE ID='MNDNAN001';

UPDATE MENUDYNAMIQUE
SET LIBELLE='éditer Ristourne ',RANG=1, NIVEAU=3, ID_PERE='MDO000005612345'
WHERE ID='MNDN00050500002';
UPDATE MENUDYNAMIQUE
SET LIBELLE='Liste des ristounes',RANG=2, NIVEAU=3, ID_PERE='MDO000005612345'
WHERE ID='MNDN00050500002L';
UPDATE MENUDYNAMIQUE
SET RANG=9, NIVEAU=2
WHERE ID='MDO0000056';
UPDATE MENUDYNAMIQUE
SET LIBELLE='par Chiffre d''affaire'
WHERE ID='MNDN0000000111';
UPDATE MENUDYNAMIQUE
SET LIBELLE='Par client'
WHERE ID='MNDN0000000112';