INSERT INTO MENUDYNAMIQUE
(ID, LIBELLE, ICONE, HREF, RANG, NIVEAU, ID_PERE)
VALUES('MENUDYN01908001', 'Compteur', 'fas fa-boxes', NULL, 3, 2, 'MENUDYN00304001');

INSERT INTO MENUDYNAMIQUE
(ID, LIBELLE, ICONE, HREF, RANG, NIVEAU, ID_PERE)
VALUES('MENUDYN01908002', 'Création', 'fa fa-plus', 'module.jsp?but=compteur/compteur-saisie.jsp', 1, 3, 'MENUDYN01908001');
INSERT INTO MENUDYNAMIQUE
(ID, LIBELLE, ICONE, HREF, RANG, NIVEAU, ID_PERE)
VALUES('MENUDYN01908003', 'Liste', 'fa fa-list', 'module.jsp?but=compteur/compteur-liste.jsp', 2, 3, 'MENUDYN01908001');


CREATE OR REPLACE VIEW COMPTEURLIB 
AS 
SELECT 
c.*,
f.LIBELLE AS idfabricationlib,
m.VAL AS idmachinelib,
CASE 
	WHEN c.etat = 0 
	THEN 'ANNULÉE'
	WHEN c.etat = 1 
	THEN 'CRÉE'
	WHEN c.etat = 11 
	THEN 'VISÉE'
END AS etatlib
FROM COMPTEUR c 
LEFT JOIN FABRICATION f ON f.id = c.idfabrication
LEFT JOIN MACHINE m ON m.id = c.idmachine
;

CREATE or replace VIEW COMPTEURLIBCREER 
AS 
SELECT 
*
FROM COMPTEURLIB 
WHERE etat = 1;


CREATE or replace VIEW COMPTEURLIBVISER 
AS 
SELECT 
*
FROM COMPTEURLIB 
WHERE etat = 11;


CREATE or replace VIEW COMPTEURLIBANNULER 
AS 
SELECT 
*
FROM COMPTEURLIB 
WHERE etat = 0;

CREATE VIEW FabricationFILLEPETRI 
AS 
SELECT 
f.*
FROM FABRICATIONFILLE f 
LEFT JOIN AS_INGREDIENTS ai ON ai.id = f.IDINGREDIENTS  
WHERE ai.IDFOURNISSEUR ='oui' ;

CREATE VIEW PROCESSFABPETRI 
AS 
SELECT 
p.* 
FROM PROCESS p 
LEFT JOIN FABRICATION f ON f.ID = p.REFOBJET 
LEFT JOIN FABRICATIONFILLE f2 ON f2.IDMERE = f.ID 
LEFT JOIN AS_INGREDIENTS ai ON ai.id = f2.IDINGREDIENTS  
WHERE ai.IDFOURNISSEUR ='oui' 
AND  p."ACTION"  = 'terminer';

UPDATE  AS_INGREDIENTS ai SET ai.IDFOURNISSEUR ='oui' 
WHERE ai.ID IN ('ING000T0131',
'ING000T0138',
'IG000430',
'IG000444',
'IG000466',
'ING000T0145',
'ING000T0152',
'ING000T0159',
'ING000T0166',
'ING000T0172',
'ING000T0179',
'IG000445');