CREATE OR REPLACE VIEW TRANSFERTSTOCKCPL AS 
  SELECT
t.ID ,
t.DESIGNATION ,
t.IDMAGASINDEPART ,
m.VAL AS IDMAGASINDEPARTLIB,
t.IDMAGASINARRIVE ,
m2.VAL AS IDMAGASINARRIVELIB,
t.DATY ,
t.ETAT ,
t.idOf,
CASE
	WHEN t.ETAT = 0
	THEN 'ANNULEE'
	WHEN t.ETAT = 1
	THEN 'CREE'
	WHEN t.ETAT = 11
	THEN 'VISEE'
END AS ETATLIB
FROM TRANSFERTSTOCK t
LEFT JOIN MAGASINPOINT m ON m.ID = t.IDMAGASINDEPART
LEFT JOIN MAGASINPOINT m2 ON m2.ID = t.IDMAGASINARRIVE ;