CREATE OR REPLACE FORCE VIEW "SOCOBIS1205"."MAGASINLIB" ("ID", "VAL", "DESCE", "IDPOINT", "IDPOINTLIB", "IDTYPEMAGASIN", "IDTYPEMAGASINLIB", "IDPRODUIT", "IDPRODUITLIB") AS
SELECT
    m.ID ,
    m.VAL ,
    m.DESCE ,
    m.IDPOINT ,
    p.VAL AS IDPOINTLIB,
    m.IDTYPEMAGASIN ,
    t.VAL AS IDTYPEMAGASINLIB,
    m.IDPRODUIT ,
    p2.VAL AS IDPRODUITLIB
FROM MAGASIN2 m
         LEFT JOIN POINT p ON p.ID = m.IDPOINT
         LEFT JOIN TYPEMAGASIN t ON t.ID = m.IDTYPEMAGASIN
         LEFT JOIN PRODUIT p2 ON p2.ID = m.IDPRODUIT ;