CREATE OR REPLACE FORCE VIEW V_ETATSTOCK_ING AS 
  SELECT 
    aim.ID AS ID,
    p.LIBELLE AS idproduitLib,
    p.CATEGORIEINGREDIENT,
    tp.DESCE AS idtypeproduitlib,
    aim.IDMAGASIN,
    mag.DESCE AS idmagasinlib,
    NVL(MAX(m.DATY),TO_DATE('01-01-2001', 'DD-MM-YYYY')) AS dateDernierMouvement,
    CAST(SUM(NVL(f.ENTREE, 0)) - SUM(NVL(f.SORTIE, 0)) AS NUMBER(30,2)) AS QUANTITE,
    CAST(SUM(NVL(f.ENTREE, 0)) AS NUMBER(30,2)) AS ENTREE,
    CAST(SUM(NVL(f.SORTIE, 0)) AS NUMBER(30,2)) AS SORTIE,
    CAST(SUM(NVL(f.ENTREE, 0)) - SUM(NVL(f.SORTIE, 0)) AS NUMBER(30,2)) AS reste,
    p.UNITE,
    u.DESCE AS idunitelib,
    CAST(NVL(p.PV, 0) AS NUMBER(30, 2)) AS PUVENTE,
    mag.IDPOINT,
    mag.IDTYPEMAGASIN,
    p.SEUILMIN,
    p.SEUILMAX
FROM AS_INGREDIENTS_MAGASIN aim
LEFT JOIN AS_INGREDIENTS p ON aim.ID = p.ID
LEFT JOIN CATEGORIEINGREDIENT tp ON p.CATEGORIEINGREDIENT = tp.ID
LEFT JOIN MAGASINPOINT mag ON aim.IDMAGASIN = mag.ID
LEFT JOIN AS_UNITE u ON p.UNITE = u.ID
LEFT JOIN MVTSTOCK m ON m.IDMAGASIN = aim.IDMAGASIN AND m.ETAT = 11
LEFT JOIN MVTSTOCKFILLE f ON f.IDMVTSTOCK = m.ID AND f.IDPRODUIT = aim.ID
GROUP BY 
    aim.ID, 
    p.LIBELLE, 
    p.CATEGORIEINGREDIENT,
    tp.DESCE,
    aim.IDMAGASIN,
    mag.DESCE,
    p.UNITE,
    u.DESCE,
    p.PV,
    mag.IDPOINT,
    mag.IDTYPEMAGASIN,
    p.SEUILMIN,
    p.SEUILMAX;
