ALTER TABLE FACTUREFOURNISSEURFILLE ADD QTETEMP NUMBER(30,10)  ;

UPDATE FACTUREFOURNISSEURFILLE SET QTETEMP = QTE WHERE 1=1;

ALTER TABLE FACTUREFOURNISSEURFILLE  DROP COLUMN QTE ;

ALTER TABLE FACTUREFOURNISSEURFILLE RENAME COLUMN QTETEMP TO  QTE ;