INSERT INTO USERMENU
(ID, REFUSER, IDMENU, IDROLE, CODESERVICE, CODEDIR, INTERDIT)
VALUES('USRMENCHFAB0085554', '*', 'MNDN0005050001', 'dg', NULL, NULL, 1);

CREATE OR REPLACE  VIEW FFFILLERESTEALIVRER (ID, IDFACTUREFOURNISSEUR, IDPRODUIT, QTE, PU, REMISES, IDBCDETAIL, TVA,idproduitlib,idunite,unitelib) AS 
SELECT
	f.id,
	f.IDFACTUREFOURNISSEUR,
	f.IDPRODUIT,
	f.QTE -nvl(sum(abf.QUANTITE), 0) AS qte ,
	f.PU ,
	f.REMISES ,
	f.IDBCDETAIL,
	f.TVA,
	ai.libelle AS idproduitlib,
	ai.unite,
	uni.val AS unitelib
FROM
	FACTUREFOURNISSEURFILLE f
LEFT JOIN AS_BONDELIVRAISON_FILLE abf ON
	f.ID = abf.IDBC_FILLE
LEFT JOIN AS_INGREDIENTS ai ON f.idproduit=ai.id
LEFT JOIN AS_unite uni ON uni.id=ai.unite
GROUP BY
	f.id,
	f.IDFACTUREFOURNISSEUR,
	f.IDPRODUIT,
	f.QTE ,
	f.PU ,
	f.REMISES ,
	f.IDBCDETAIL,
	f.TVA,
	ai.libelle,
	ai.unite,
	uni.val;
	

	
ALTER TABLE AS_BONDELIVRAISON_FILLE ADD PU number(30,2);
-- SOCOBISPROD0707.AS_BONDELIVRAISON_FILLE_VIDE source

CREATE OR REPLACE  VIEW AS_BONDELIVRAISON_FILLE_VIDE (ID, PRODUIT, PRODUITLIB, QUANTITE, UNITE, NUMBL, IDDETAILSFACTUREFOURNISSEUR, IDBC_FILLE, REMARQUE, IDBC, DATY, ETAT, MAGASIN, UNITELIB, MAGASINLIB,pu) AS 
  SELECT
cast(' ' as varchar(100)) AS ID,
cast(' ' as varchar(255)) AS PRODUIT,
cast(' ' as varchar(255)) AS PRODUITLIB ,
cast(-1 as NUMBER(10,2) ) AS QUANTITE ,
cast(' ' as varchar(100)) AS UNITE,
cast(' ' as varchar(100)) AS NUMBL,
cast(' ' as varchar(100)) AS IDDETAILSFACTUREFOURNISSEUR,
cast(' ' as varchar(100)) AS IDBC_FILLE ,
cast(' ' as varchar(200)) AS REMARQUE ,
cast(' ' as varchar(100)) AS IDBC ,
cast(NULL as DATE ) AS DATY ,
cast(-1 as int ) AS ETAT,
cast(' ' as varchar(500)) AS MAGASIN ,
cast(' ' as varchar(255)) AS UNITELIB ,
cast(' ' as varchar(255)) AS MAGASINLIB,
cast(-1 as NUMBER(10,2) ) AS pu 
FROM dual ;

-- SOCOBISPROD0707.AS_BONDELIVRAISON_LIBCPL source

CREATE OR REPLACE  VIEW AS_BONDELIVRAISON_LIBCPL (ID, PRODUIT, NUMBL, QUANTITE, IDDETAILSFACTUREFOURNISSEUR, UNITE, IDBC_FILLE, REMARQUE, IDBC, DATY, ETAT, MAGASIN, PRODUITLIB, UNITELIB, MAGASINLIB, LIBELLEEXTACTE,pu,montant) AS 
  SELECT
	bl.ID,
	bl.PRODUIT,
	bl.NUMBL,
	bl.QUANTITE,
	bl.IDDETAILSFACTUREFOURNISSEUR,
	bl.UNITE,
	bl.IDBC_FILLE,
	AB.REMARQUE,
	AB.IDBC,
	AB.DATY,
	AB.ETAT,
	AB.MAGASIN,
	p.libelle AS PRODUITlib,
	u.VAL AS UNITElib,
	m.VAL AS magasinlib,
	p.LIBELLEEXTACTE,
	bl.pu,
	CAST(bl.pu * bl.quantite AS NUMBER(30, 2)) AS montant
FROM
	As_BonDeLivraison_Fille bl
LEFT JOIN AS_BONDELIVRAISON AB ON
	AB.ID = bl.NUMBL
LEFT JOIN AS_INGREDIENTS p ON
	bl.PRODUIT = p.ID
LEFT JOIN AS_UNITE  u ON
	bl.UNITE = u.ID
LEFT JOIN MAGASIN m ON
	ab.MAGASIN = m.ID;

	
CREATE OR REPLACE  VIEW RAPPROCHEMENT_BF_FOURNISSEUR (ID, PRODUIT, NUMBL, QUANTITE, IDDETAILSFACTUREFOURNISSEUR, UNITE, IDBC_FILLE, REMARQUE, IDBC, DATY, ETAT, MAGASIN, PRODUITLIB, UNITELIB, MAGASINLIB, LIBELLEEXACTE, QTEENTREE, RESTEASORTIR,PU) AS 
  SELECT
abcc.ID,
abcc.PRODUIT,
abcc.NUMBL,
abcc.QUANTITE,
abcc.IDDETAILSFACTUREFOURNISSEUR,
abcc.UNITE,
abcc.IDBC_FILLE,
abcc.REMARQUE,
abcc.IDBC,
abcc.DATY,
abcc.ETAT,
abcc.MAGASIN,
abcc.PRODUITLIB,
abcc.UNITELIB,
abcc.MAGASINLIB,
abcc.LIBELLEEXTACTE AS LIBELLEEXACTE,
nvl(m.qteEntree,0) AS qteEntree,
abcc.QUANTITE - nvl(m.qteEntree,0) AS resteASortir,
abcc.pu
FROM AS_BONDELIVRAISON_LIBCPL abcc
LEFT JOIN entreeproduit m ON m.idproduit = abcc.produit
LEFT JOIN MVTSTOCK mv ON mv.idobjet = abcc.numbl ;