--MENU
--Gestion électronique des fichiers 
--lasa /artisanat ilay izy dia lasa manao 404 Not Found

UPDATE MENUDYNAMIQUE
SET  HREF='module.jsp?but=filemanager/file-liste-2.jsp'
WHERE ID='MENUP0011V';

--MENU
--Comptabilité
--‘Écriture’ no izy
--‘État’ no izy

UPDATE MENUDYNAMIQUE
SET LIBELLE='État'
WHERE ID='MNDN285';
UPDATE MENUDYNAMIQUE
SET LIBELLE='Écriture'
WHERE ID='MNDSN287';


CREATE OR REPLACE  VIEW ST_INGREDIENTSAUTO (ID, LIBELLE, SEUIL, UNITE, QUANTITEPARPACK, PU, ACTIF, PHOTO, CALORIE, DURRE, COMPOSE, CATEGORIEINGREDIENT, IDFOURNISSEUR, DATY, QTELIMITE, PV, LIBELLEVENTE, SEUILMIN, SEUILMAX, PUACHATUSD, PUACHATEURO, PUACHATAUTREDEVISE, PUVENTEUSD, PUVENTEEURO, PUVENTEAUTREDEVISE, ISVENTE, ISACHAT, COMPTE_VENTE, COMPTE_ACHAT, COMPTE,UNITELIB) AS 
  SELECT
    ai.ID,ai.LIBELLE,ai.SEUIL,ai.UNITE,ai.QUANTITEPARPACK,ai.PU,ai.ACTIF,ai.PHOTO,ai.CALORIE,ai.DURRE,ai.COMPOSE,ai.CATEGORIEINGREDIENT,ai.IDFOURNISSEUR,ai.DATY,ai.QTELIMITE,ai.PV,ai.LIBELLEVENTE,ai.SEUILMIN,ai.SEUILMAX,ai.PUACHATUSD,ai.PUACHATEURO,ai.PUACHATAUTREDEVISE,ai.PUVENTEUSD,ai.PUVENTEEURO,ai.PUVENTEAUTREDEVISE,ai.ISVENTE,ai.ISACHAT,ai.COMPTE_VENTE,ai.COMPTE_ACHAT,
    CASE
        WHEN ai.COMPTE_VENTE IS NOT NULL THEN ai.COMPTE_VENTE
        ELSE ai.COMPTE_ACHAT
    END AS compte,
    au.VAL AS UNITELIB
FROM AS_INGREDIENTS ai
LEFT JOIN AS_UNITE au  ON au.id = ai.UNITE ;

UPDATE MENUDYNAMIQUE
SET LIBELLE='Mise en Carton', ICONE='fa fa-book', HREF=NULL, RANG=7, NIVEAU=2, ID_PERE='MNDN000000001ESORINA'
WHERE ID='MNDN0029040001';

--MENU orthographe
--Achat> ‘Récéption Produit’

UPDATE MENUDYNAMIQUE
SET LIBELLE='Récéption Produit'
WHERE ID='MNDN000000002';

--MENU
--Livraison interne
--Saisie : tsy mandeha
--Liste : tsy mandeha
--esorina koa ito

UPDATE MENUDYNAMIQUE
SET LIBELLE='Livraison Interne', ICONE='fa fa-file-text', HREF=NULL, RANG=7, NIVEAU=2, ID_PERE='MNDN000000003ESORINA'
WHERE ID='MNDN00030040958';


-- 
--MENU
--Insertion par categorie : miverina in-2
-- 

UPDATE MENUDYNAMIQUE
SET LIBELLE='Saisie par categorie', ICONE='fa fa-plus', HREF='module.jsp?but=inventaire/inventaire-categorie-saisie.jsp', RANG=3, NIVEAU=3, ID_PERE='MNDN000000021ESORINA'
WHERE ID='MNDN000000028a';