--FabricationFilleCpl
--asiana idMachine
--asiana idMachineLib (machine.val)
--ity lesy mba atao aty an'ilay local 

CREATE OR REPLACE  VIEW FABRICATIONFILLECPL (ID, IDINGREDIENTS, LIBELLE, REMARQUE, IDMERE, DATYBESOIN, QTE, IDUNITE, PU, IDINGREDIENTSLIB, OPERATEUR, IDUNITELIB, IDBCFILLE,IDMACHINE,IDMACHINELIB) AS 
  SELECT
	f.ID,
	f.IDINGREDIENTS,
	f.LIBELLE,
	f.REMARQUE,
	f.IDMERE,
	f.DATYBESOIN,
	f.QTE,
	f.IDUNITE,
	f.PU,
	ai.LIBELLE AS idingredientsLib,
	p.NOM || ' - ' || p.TELEPHONE AS operateur,
	au.val AS IDUNITELIB,
	f.IDBCFILLE ,
	f.IDMACHINE,
	m.val AS IDMACHINELIB
FROM
	FABRICATIONFILLE f
LEFT JOIN AS_INGREDIENTS ai ON
	ai.id = f.IDINGREDIENTS
LEFT JOIN PERSONNEL p ON
	p.ID = f.OPERATEUR
LEFT JOIN AS_UNITE au ON
	au.id = f.IDUNITE
LEFT JOIN MACHINE m ON m.ID = f.IDMACHINE  ;


--MAGASINLIB
-- 
--amin'ity vue ity lesy atao join as_ingredients fa tsy produit

CREATE OR REPLACE  VIEW MAGASINLIB (ID, VAL, DESCE, IDPOINT, IDPOINTLIB, IDTYPEMAGASIN, IDTYPEMAGASINLIB, IDPRODUIT, IDPRODUITLIB) AS 
  SELECT
    m.ID ,
    m.VAL ,
    m.DESCE ,
    m.IDPOINT ,
    p.VAL AS IDPOINTLIB,
    m.IDTYPEMAGASIN ,
    t.VAL AS IDTYPEMAGASINLIB,
    m.IDPRODUIT ,
    p2.LIBELLE AS IDPRODUITLIB
FROM MAGASIN2 m
         LEFT JOIN POINT p ON p.ID = m.IDPOINT
         LEFT JOIN TYPEMAGASIN t ON t.ID = m.IDTYPEMAGASIN
         LEFT JOIN AS_INGREDIENTS p2 ON p2.ID = m.IDPRODUIT ;