CREATE OR REPLACE VIEW TRANSFERTSTOCKDETAILSCPL AS
SELECT
    t.ID ,
    t.IDTRANSFERTSTOCK ,
    t2.DESIGNATION AS IDTRANSFERTSTOCKLIB,
    t.IDPRODUIT ,
    p.libelle AS IDPRODUITLIB,
    CAST(t.QUANTITE AS NUMBER(30,2)) AS QUANTITE,
    CAST(t.PU AS NUMBER(30, 2)) AS PU
FROM TRANSFERTSTOCKDETAILS t
         LEFT JOIN TRANSFERTSTOCK t2 ON t2.ID = t.IDTRANSFERTSTOCK
         LEFT JOIN AS_INGREDIENTS  p ON p.ID = t.IDPRODUIT;