CREATE VIEW COMPTEURLIB 
AS 
SELECT 
c.*,
f.LIBELLE AS idfabricationlib,
m.VAL AS idmachinelib
FROM COMPTEUR c 
LEFT JOIN FABRICATION f ON f.id = c.idfabrication
LEFT JOIN MACHINE m ON m.id = c.idmachine
;

ALTER TABLE COMPTEUR ADD etat int;

--idOrigine amn TABLE COMPTEUR (FK Magasin2)

ALTER TABLE COMPTEUR ADD idOrigine varchar(255) CONSTRAINT compteur_origine_fk REFERENCES MAGASIN2(id);

CREATE OR REPLACE  VIEW COMPTEURLIB (ID, NOMBRE, IDFABRICATION, IDMACHINE, DATY, HEURE, DEBUT, ETAT, IDFABRICATIONLIB, IDMACHINELIB,idOrigine) AS 
  SELECT 
c.ID,c.NOMBRE,c.IDFABRICATION,c.IDMACHINE,c.DATY,c.HEURE,c.DEBUT,c.ETAT,
f.LIBELLE AS idfabricationlib,
m.VAL AS idmachinelib,
c.idOrigine
FROM COMPTEUR c 
LEFT JOIN FABRICATION f ON f.id = c.idfabrication
LEFT JOIN MACHINE m ON m.id = c.idmachine
;

--TABLE MAGASIN2
--esorina n contraint IDPRODUIT

ALTER TABLE MAGASIN2 DROP CONSTRAINT MAGASIN_PRODUIT_FK ;