


UPDATE CAISSE SET IDPOINT = NULL WHERE 1=1 ;

UPDATE CAISSE SET IDMAGASIN  = NULL WHERE 1=1 ;

DELETE FROM MAGASIN2 m WHERE 1=1;

UPDATE MVTSTOCK SET IDPOINT = NULL WHERE 1=1 ;

UPDATE AS_BONDELIVRAISON SET MAGASIN = NULL WHERE 1=1 ;

DELETE FROM POINT p  WHERE 1=1;

--données Tiavina
--point
--central
--transit
--divers

INSERT INTO POINT
(ID, VAL, DESCE)
VALUES('PNT000084', 'central', 'central');
INSERT INTO POINT
(ID, VAL, DESCE)
VALUES('PNT000123', 'transit', 'transit');
INSERT INTO POINT
(ID, VAL, DESCE)
VALUES('PNT000125', 'divers', 'divers');

--magasin  
--Magasin central biscuiterie 
--idpoint central
--Magasin central confiserie
--idpoint central
--Magasin transit matière première
--idpoint transit
--Magasin transit emballage
--idpoint transit
--Magasin produit fini
--idpoint divers
--Magasin intermédiaire
--idpoint divers
--Magasin gasoil
--idpoint divers
--Magasin gaz 1
--idpoint divers
--Magasin gaz 2
--idpoint divers


INSERT INTO MAGASIN2
(ID, VAL, DESCE, IDPOINT, IDPRODUIT, IDTYPEMAGASIN, ETAT)
VALUES('PHARM001', 'Magasin central biscuiterie', 'Magasin central biscuiterie', 'PNT000084', NULL, NULL, 12);
INSERT INTO MAGASIN2
(ID, VAL, DESCE, IDPOINT, IDPRODUIT, IDTYPEMAGASIN, ETAT)
VALUES('PHARM002', 'Magasin central confiserie', 'Magasin central confiserie', 'PNT000084', NULL, NULL, 11);
INSERT INTO MAGASIN2
(ID, VAL, DESCE, IDPOINT, IDPRODUIT, IDTYPEMAGASIN, ETAT)
VALUES('PHARM003', 'Magasin transit matière première', 'Magasin transit matière première', 'PNT000123', NULL, NULL, 11);
INSERT INTO MAGASIN2
(ID, VAL, DESCE, IDPOINT, IDPRODUIT, IDTYPEMAGASIN, ETAT)
VALUES('PHARM04', 'Magasin transit emballage', 'Magasin transit emballage', 'PNT000123', NULL, NULL, 11);
INSERT INTO MAGASIN2
(ID, VAL, DESCE, IDPOINT, IDPRODUIT, IDTYPEMAGASIN, ETAT)
VALUES('PHARM005', 'Magasin produit fini', 'Magasin produit fini', 'PNT000125', NULL, NULL, 11);
INSERT INTO MAGASIN2
(ID, VAL, DESCE, IDPOINT, IDPRODUIT, IDTYPEMAGASIN, ETAT)
VALUES('PHARM006', 'Magasin intermédiaire', 'Magasin intermédiaire', 'PNT000125', NULL, NULL, 11);
INSERT INTO MAGASIN2
(ID, VAL, DESCE, IDPOINT, IDPRODUIT, IDTYPEMAGASIN, ETAT)
VALUES('PHARM007', 'Magasin gasoil', 'Magasin gasoil', 'PNT000125', NULL, NULL, 11);
INSERT INTO MAGASIN2
(ID, VAL, DESCE, IDPOINT, IDPRODUIT, IDTYPEMAGASIN, ETAT)
VALUES('PHARM008', 'Magasin gaz 1', 'Magasin gaz 1', 'PNT000125', NULL, NULL, 11);
INSERT INTO MAGASIN2
(ID, VAL, DESCE, IDPOINT, IDPRODUIT, IDTYPEMAGASIN, ETAT)
VALUES('PHARM009', 'Magasin gaz 2', 'Magasin gaz 2', 'PNT000125', NULL, NULL, 11);



INSERT INTO USERMENU
(ID, REFUSER, IDMENU, IDROLE, CODESERVICE, CODEDIR, INTERDIT)
VALUES('USRMENMGCTRL007', NULL, 'MNDN000000002', 'magcentral', NULL, NULL, NULL);

INSERT INTO USERMENU
(ID, REFUSER, IDMENU, IDROLE, CODESERVICE, CODEDIR, INTERDIT)
VALUES('USRMENMGCTRL006', NULL, 'MNDN000000001', 'magcentral', NULL, NULL, NULL);

INSERT INTO USERMENU
(ID, REFUSER, IDMENU, IDROLE, CODESERVICE, CODEDIR, INTERDIT)
VALUES('USRMENMGCTRL008', NULL, 'MNDN00001', 'magcentral', NULL, NULL, NULL);

ALTER TABLE INVENTAIREFILLE ADD QUANTITETHEORIQUETEMP NUMBER(30,10)  ;
 
UPDATE INVENTAIREFILLE SET QUANTITETHEORIQUETEMP = QUANTITETHEORIQUE WHERE 1=1;
 
ALTER TABLE INVENTAIREFILLE  DROP COLUMN QUANTITETHEORIQUE ;
 
ALTER TABLE INVENTAIREFILLE RENAME COLUMN QUANTITETHEORIQUETEMP TO  QUANTITETHEORIQUE ;
 
ALTER TABLE INVENTAIREFILLE ADD QUANTITETEMP NUMBER(30,10)  ;
 
UPDATE INVENTAIREFILLE SET QUANTITETEMP = QUANTITE WHERE 1=1;
 
ALTER TABLE INVENTAIREFILLE  DROP COLUMN QUANTITE ;
 
ALTER TABLE INVENTAIREFILLE RENAME COLUMN QUANTITETEMP TO  QUANTITE ;