--DEMANDETRANSFERTFILLE
--pu quantite

ALTER TABLE DEMANDETRANSFERTFILLE ADD putemp NUMBER(30,5); 

ALTER TABLE DEMANDETRANSFERTFILLE ADD quantitetemp NUMBER(30,5); 

UPDATE DEMANDETRANSFERTFILLE SET putemp = pu WHERE 1=1;

UPDATE DEMANDETRANSFERTFILLE SET quantitetemp = QUANTITE WHERE 1=1;

ALTER TABLE DEMANDETRANSFERTFILLE DROP COLUMN pu;

ALTER TABLE DEMANDETRANSFERTFILLE DROP COLUMN QUANTITE;

ALTER TABLE DEMANDETRANSFERTFILLE RENAME COLUMN putemp TO pu;

ALTER TABLE DEMANDETRANSFERTFILLE RENAME COLUMN quantitetemp TO QUANTITE;