

CREATE OR REPLACE  VIEW RESSOURCEPARFABRICATIONCOMPLET (ID, IDFABRICATION, IDPOSTEDEFAUT, IDRESSOURCE, MATRICULE, IDOF, ETAT, TEMPORAIRE, IDQUALIFICATIONEFFECTIVE, IDCATEGORIE, IDPOSTE, IDPOSTELIB, IDQUALIFICATIONDEFAUT, TAUXHORAIRE, HS, MN, JF, HD, IF, ETATLIB,idRessourcelib) AS 
  SELECT 
r.id,
r.idFabrication,
r.idPoste AS idPosteDefaut,
r.idRessource,
p.matricule,
f.IDOF,
r.etat ,
p.TEMPORAIRE,
p.IDQUALIFICATION AS IdQualificationEffective,
c.IDCATEGORIE,
c.idPoste ,
po.VAL AS idPostelib,
c.IDQUALIFICATION AS IdQualificationDefaut,
CAST(c.montant/((40*52)/12) AS NUMBER(30,2) ) AS tauxhoraire,
h.HS ,
h.MN ,
h.JF ,
h.HD ,
h.IF ,
CASE 
	WHEN r.etat = 0 
	THEN 'ANNULEE'
	WHEN r.etat = 1 
	THEN 'CREE'
	WHEN r.etat = 11 
	THEN 'VISEE'
END AS etatlib,
pip.CTURGENCE_NOM_PRENOM AS idRessourcelib
FROM ressourceParFabrication r 
LEFT JOIN PAIE_INFO_PERSONNEL p ON p.id = r.idRessource
LEFT JOIN CATEGORIE_QUALIFICATION c ON c.idposte = r.idposte
LEFT JOIN FABRICATION f ON f.id = r.idFabrication
LEFT JOIN heureSupFabrication h ON h.idRessParFab = r.id
LEFT JOIN POSTE po ON po.id =  c.idPoste 
LEFT JOIN PAIE_INFO_PERSONNEL pip ON pip.id = r.idRessource ;

ALTER TABLE HEURESUPFABRICATION ADD remarque varchar(255);

CREATE OR REPLACE  VIEW HEURESUPFABRICATION_CPL (ID, IDRESSPARFAB, HS, MN, JF, HD, IF, ETAT, REMARQUE, IDPERSONNE, IDFABRICATION, ETATLIB, IDPERSONNELIB,MATRICULE,TAUXHORAIRE,TAUXHORAIREEFFECTIVE) AS 
  SELECT 
h.ID,h.IDRESSPARFAB,h.HS,h.MN,h.JF,h.HD,h.IF,h.ETAT,h.REMARQUE,
p.id AS  idPersonne,
r.idFabrication,
CASE 
	WHEN h.etat=0
	THEN 'ANNULEE'
	WHEN h.etat=1
	THEN 'CREE'
	WHEN h.etat=11
	THEN 'VISEE'
END AS etatlib,
p.CTURGENCE_NOM_PRENOM AS idPersonnelib,
p.MATRICULE,
r.TAUXHORAIRE,
CAST(nvl(c.montant,0)/((40*52)/12) AS NUMBER(30,2) ) AS TAUXHORAIREEFFECTIVE
FROM HEURESUPFABRICATION h 
LEFT JOIN RESSOURCEPARFABRICATIONCOMPLET r ON r.id = h.IDRESSPARFAB 
LEFT JOIN PAIE_INFO_PERSONNEL p ON p.id = r.idRessource
LEFT JOIN CATEGORIE_QUALIFICATION c ON c.IDQUALIFICATION = p.IDQUALIFICATION;