CREATE OR REPLACE VIEW MVTSTOCKFILLEENTREEFAB AS
select st.ID,st.IDMVTSTOCK,st.IDPRODUIT,ai.LIBELLE AS IDPRODUITLIB,st.ENTREE,st.SORTIE,st.IDVENTEDETAIL,st.IDTRANSFERTDETAIL,st.PU,st.MVTSRC,st.RESTE,st.DESIGNATION,st.IDFAB 
from MVTSTOCKFILLEFAB st
LEFT JOIN AS_INGREDIENTS ai
ON st.IDPRODUIT = ai.id
WHERE st.SORTIE <= 0;

CREATE OR REPLACE VIEW MVTSTOCKFILLESORITEFAB AS
select st.ID,st.IDMVTSTOCK,st.IDPRODUIT,ai.LIBELLE AS IDPRODUITLIB,st.ENTREE,st.SORTIE,st.IDVENTEDETAIL,st.IDTRANSFERTDETAIL,st.PU,st.MVTSRC,st.RESTE,st.DESIGNATION,st.idFab
from MVTSTOCKFILLEFAB st
LEFT JOIN AS_INGREDIENTS ai
ON st.IDPRODUIT = ai.id
WHERE st.ENTREE  <= 0;

CREATE OR REPLACE VIEW MVTSTOCKFILLERESIDUFAB AS
SELECT
    entree.ID,
    entree.IDPRODUIT,
    entree.IDPRODUITLIB,
    entree.ENTREE,
    entree.PU AS PU,
    entree.RESTE AS RESTE,
    entree.DESIGNATION,
    entree.IDFAB
FROM
    MVTSTOCKFILLEENTREEFAB entree
JOIN
    MVTSTOCKFILLESORITEFAB sortie
ON
    entree.IDPRODUIT = sortie.IDPRODUIT
AND
    entree.IDFAB = sortie.IDFAB;
 