ALTER TABLE MVTSTOCKFILLE ADD entreetemp NUMBER(30,5);

ALTER TABLE MVTSTOCKFILLE ADD sortietemp NUMBER(30,5);

ALTER TABLE MVTSTOCKFILLE ADD putemp NUMBER(30,5);

ALTER TABLE MVTSTOCKFILLE ADD restetemp NUMBER(30,5);

UPDATE MVTSTOCKFILLE SET entreetemp = entree WHERE 1=1;

UPDATE MVTSTOCKFILLE SET sortietemp = sortie WHERE 1=1;

UPDATE MVTSTOCKFILLE SET putemp = pu WHERE 1=1;

UPDATE MVTSTOCKFILLE SET restetemp = reste WHERE 1=1;

ALTER TABLE MVTSTOCKFILLE DROP COLUMN entree;

ALTER TABLE MVTSTOCKFILLE DROP COLUMN sortie;

ALTER TABLE MVTSTOCKFILLE DROP COLUMN reste;

ALTER TABLE MVTSTOCKFILLE DROP COLUMN pu;

ALTER TABLE MVTSTOCKFILLE RENAME COLUMN entreetemp TO entree;

ALTER TABLE MVTSTOCKFILLE RENAME COLUMN sortietemp TO sortie;

ALTER TABLE MVTSTOCKFILLE RENAME COLUMN putemp TO pu;

ALTER TABLE MVTSTOCKFILLE RENAME COLUMN restetemp TO reste;


CREATE OR REPLACE VIEW MVTSTOCKFILLELIB AS
SELECT
    m.ID ,
    m.IDMVTSTOCK ,
    m.IDPRODUIT ,
    p.libelle  AS IDPRODUITLIB,
    m.ENTREE ,
    m.SORTIE ,
    m.IDVENTEDETAIL ,
    '' AS IDVENTEDETAILLIB,
    m.IDTRANSFERTDETAIL ,
    '' AS IDTRANSFERTDETAILLIB,
    m2.DATY ,
    m2.IDMAGASIN ,
    m3.VAL AS IDMAGASINLIB,
    m.pu,
    cast(m.pu*m.ENTREE+(m.pu*m.sortie) as number(20,5)) as montant,
    p.LIBELLE,
    m.MVTSRC,
    p.libelle AS libelleexacte
FROM MVTSTOCKFILLE m
         LEFT JOIN AS_INGREDIENTS  p ON p.ID = m.IDPRODUIT
         LEFT JOIN MVTSTOCK m2 ON m2.ID = m.IDMVTSTOCK
         LEFT JOIN MAGASIN2 m3 ON m3.ID = m2.IDMAGASIN;

ALTER TABLE INVENTAIREFILLE ADD putemp NUMBER(30,5);

UPDATE INVENTAIREFILLE SET putemp = pu WHERE 1=1;
ALTER TABLE INVENTAIREFILLE DROP COLUMN pu;

ALTER TABLE INVENTAIREFILLE RENAME COLUMN putemp TO pu;


ALTER TABLE TRANSFERTSTOCKDETAILS ADD putemp NUMBER(30,5);
ALTER TABLE TRANSFERTSTOCKDETAILS ADD quantitetemp NUMBER(30,5);

UPDATE TRANSFERTSTOCKDETAILS SET putemp = pu WHERE 1=1;
UPDATE TRANSFERTSTOCKDETAILS SET quantitetemp = quantite WHERE 1=1;
ALTER TABLE TRANSFERTSTOCKDETAILS DROP COLUMN pu;
ALTER TABLE TRANSFERTSTOCKDETAILS DROP COLUMN quantite;

ALTER TABLE TRANSFERTSTOCKDETAILS RENAME COLUMN putemp TO pu;
ALTER TABLE TRANSFERTSTOCKDETAILS RENAME COLUMN quantitetemp TO quantite;


CREATE OR REPLACE VIEW TRANSFERTSTOCKDETAILSCPL AS
SELECT
    t.ID ,
    t.IDTRANSFERTSTOCK ,
    t2.DESIGNATION AS IDTRANSFERTSTOCKLIB,
    t.IDPRODUIT ,
    p.libelle AS IDPRODUITLIB,
    CAST(t.QUANTITE AS NUMBER(30,5)) AS QUANTITE,
    CAST(t.PU AS NUMBER(30, 5)) AS PU
FROM TRANSFERTSTOCKDETAILS t
         LEFT JOIN TRANSFERTSTOCK t2 ON t2.ID = t.IDTRANSFERTSTOCK
         LEFT JOIN AS_INGREDIENTS  p ON p.ID = t.IDPRODUIT;

CREATE OR REPLACE VIEW DEMANDETRANSFERTFILLECPL AS
SELECT
    t.ID ,
    t.IDdemandetransfert ,
    t2.DESIGNATION AS IDdemandetransfertLIB,
    t.IDPRODUIT ,
    p.libelle AS IDPRODUITLIB,
    t.QUANTITE,
    p.TYPESTOCK,
    p.UNITE,
    CAST(p.PU AS NUMBER(30, 5)) AS PU
FROM demandetransfertfille t
         LEFT JOIN demandetransfert t2 ON t2.ID = t.IDdemandetransfert
         LEFT JOIN AS_INGREDIENTS  p ON p.ID = t.IDPRODUIT;


CREATE OR REPLACE VIEW MVTSTOCKFILLEMONTANT AS
select mf."ID",mf."IDMVTSTOCK",mf."IDPRODUIT",mf."ENTREE",mf."SORTIE",mf."IDVENTEDETAIL",mf."IDTRANSFERTDETAIL",mf."PU",mf."MVTSRC",mf."RESTE",mf."DESIGNATION",cast(mf.PU*mf.ENTREE as number(30,5)) as montantEntree,cast(mf.PU*mf.SORTIE as number(30,5)) as montantSortie from MVTSTOCKFILLE mf
;


CREATE OR REPLACE VIEW TRANSFERTSTOCKDETAILSCPL AS
SELECT
    t.ID ,
    t.IDTRANSFERTSTOCK ,
    t2.DESIGNATION AS IDTRANSFERTSTOCKLIB,
    t.IDPRODUIT ,
    p.libelle AS IDPRODUITLIB,
    CAST(t.QUANTITE AS NUMBER(30,5)) AS QUANTITE,
    CAST(t.PU AS NUMBER(30, 5)) AS PU,
    t.idsource
FROM TRANSFERTSTOCKDETAILS t
         LEFT JOIN TRANSFERTSTOCK t2 ON t2.ID = t.IDTRANSFERTSTOCK
         LEFT JOIN AS_INGREDIENTS  p ON p.ID = t.IDPRODUIT;


