CREATE OR REPLACE VIEW AS_RECOFFVUE AS
SELECT
    ar.ID,ar.IDINGREDIENTS,ar.UNITE,ar.QTEAV,ar.QUANTITE,ar.IDPRODUITS,ar.IDUNITE,ar.COMPOSE,ar.NIVEAU,
    ai.LIBELLE AS libIngredients,cast(0 as number(30,10)) as resteStock,ai.TYPESTOCK
FROM AS_RECETTEOFFFABTABLE ar
         LEFT JOIN AS_INGREDIENTS ai ON ai.id = ar.IDINGREDIENTS;