ALTER TABLE FABRICATIONFILLE
ADD (nbPetris NUMBER(20,2));

CREATE OR REPLACE VIEW COMPTEURLIB AS 
  SELECT 
c.ID,c.NOMBRE,c.IDFABRICATION,c.IDMACHINE,c.DATY,c.HEURE,c.DEBUT,c.ETAT,
f.LIBELLE AS idfabricationlib,
m.VAL AS idmachinelib,
c.idOrigine
FROM COMPTEUR c 
LEFT JOIN FABRICATION f ON f.id = c.idfabrication
LEFT JOIN MACHINE m ON m.id = c.idmachine
;