ALTER TABLE HEURESUPFABRICATION ADD poste VARCHAR(255)

ALTER TABLE HEURESUPFABRICATION ADD equipe varchar(255)

CREATE TABLE "EQUIPE" 
   (	"ID" VARCHAR2(100), 
	"VAL" VARCHAR2(200), 
	"DESCE" VARCHAR2(200), 
	 CONSTRAINT "EQUIPE_PK" PRIMARY KEY ("ID")
   )
   
CREATE TABLE "EQUIPEEMP" 
   (	"ID" VARCHAR2(100), 
	"VAL" VARCHAR2(200), 
	"DESCE" VARCHAR2(200), 
	 CONSTRAINT "EQUIPEEMP_PK" PRIMARY KEY ("ID")
   )
   
   
CREATE SEQUENCE seq_equipe
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;


CREATE OR REPLACE FUNCTION getseq_equipe
   RETURN NUMBER
IS
   retour   NUMBER;
BEGIN
   SELECT seq_equipe.NEXTVAL INTO retour FROM DUAL;

   RETURN retour;
END;


CREATE SEQUENCE seq_equipeemp
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;


CREATE OR REPLACE FUNCTION getseq_equipeemp
   RETURN NUMBER
IS
   retour   NUMBER;
BEGIN
   SELECT seq_equipe.NEXTVAL INTO retour FROM DUAL;

   RETURN retour;
END;

ALTER TABLE FABRICATION ADD equipe VARCHAR(255)