-- GALLOIS_NOUVEAU.LIAISONFACTUREFOURNISSEURS definition

CREATE TABLE LIAISONFACTUREFOURNISSEURS 
   (	ID VARCHAR2(500) NOT NULL ENABLE, 
	ID1 VARCHAR2(500), 
	ID2 VARCHAR2(500), 
	MONTANT NUMBER(30,2), 
	ETAT NUMBER, 
	 PRIMARY KEY (ID)
   ) ;


CREATE SEQUENCE SEQLIAISONFACTUREFOURNISSEURS INCREMENT BY 1 MINVALUE 1 MAXVALUE 999999999999 NOCYCLE CACHE 20 NOORDER ;

CREATE OR REPLACE FUNCTION getseqliaisonfacturef
    RETURN NUMBER
    IS
    retour   NUMBER;
BEGIN
    SELECT seqliaisonfacturefournisseurs.NEXTVAL INTO retour FROM DUAL;
    RETURN retour;
END;

CREATE OR REPLACE  VIEW FACTUREFOURNISSEURCPL_FD as
 SELECT
	f.ID,
	f.IDFOURNISSEUR,
	f.IDFOURNISSEURLIB,
	f.IDMODEPAIEMENT,
	f.IDMODEPAIEMENTLIB,
	f.DATY,
	f.DESIGNATION,
	f.DATEECHEANCEPAIEMENT,
	f.ETAT,
	f.ETATLIB,
	f.REFERENCE,
	f.IDBC,
	f.IDMAGASIN,
	f.DEVISE,
	f.TAUX,
	f.IDMAGASINLIB,
	f.IDDEVISE,
	f.MONTANTTVA,
	f.MONTANTHT,
	f.MONTANTTTC,
	f.MONTANTTTCAR,
	f.MONTANTPAYE,
	f.MONTANTRESTE,
	f.TAUXDECHANGE,
	f.IDPREVISION,
	bl.id AS idbl
FROM
	FACTUREFOURNISSEURCPL f
LEFT JOIN AS_BONDELIVRAISON bl ON
	f.id = bl.IDFACTUREFOURNISSEUR
LEFT JOIN liaisonfacturefournisseurs l ON
	(f.id = l.id1
		OR f.id = l.id2)
WHERE
	bl.id IS NULL
	AND l.id IS NULL;

CREATE OR REPLACE VIEW FACTUREFOURNISSEURCPL_LIER  AS 
  SELECT
	f.ID,
	f.IDFOURNISSEUR,
	f.IDFOURNISSEURLIB,
	f.IDMODEPAIEMENT,
	f.IDMODEPAIEMENTLIB,
	f.DATY,
	f.DESIGNATION,
	f.DATEECHEANCEPAIEMENT,
	f.ETAT,
	f.ETATLIB,
	f.REFERENCE,
	f.IDBC,
	f.IDMAGASIN,
	f.DEVISE,
	f.TAUX,
	f.IDMAGASINLIB,
	f.IDDEVISE,
	f.MONTANTTVA,
	f.MONTANTHT,
	f.MONTANTTTC,
	f.MONTANTTTCAR,
	f.MONTANTPAYE,
	f.MONTANTRESTE,
	f.TAUXDECHANGE,
	f.IDPREVISION,
	l.id1
FROM
	liaisonfacturefournisseurs l
LEFT JOIN FACTUREFOURNISSEURCPL f ON
	l.id2 = f.id;

CREATE OR REPLACE  VIEW PERTE_GRPORIGINE_FACT (IDORIGINE, MONTANT, MONTANTAR) AS 
  select lf.id1 as idorigine, sum(ffc.MONTANTHT) as montant, sum(ffc.montantHT * ffc.TAUXDECHANGE) as montantar
from LIAISONFACTUREFOURNISSEURS lf
         LEFT JOIN FACTUREFOURNISSEURCPL FFC on FFC.id = lf.id2
group by lf.id1;



CREATE OR REPLACE  VIEW FACTUREFOURNISSEUR_PERTE (ID, IDFOURNISSEUR, IDMODEPAIEMENT, DATY, DESIGNATION, DATEECHEANCEPAIEMENT, ETAT, REFERENCE, IDBC, DEVISE, TAUX, IDMAGASIN, IDDEVISE, ESTPREVU, DATYPREVU, MONTANTPERTEGAIN) AS 
  SELECT f.ID,
       f.IDFOURNISSEUR,
       f.IDMODEPAIEMENT,
       f.DATY,
       f.DESIGNATION,
       f.DATEECHEANCEPAIEMENT,
       f.ETAT,
       f.REFERENCE,
       f.IDBC,
       f.DEVISE,
       f.TAUX,
       f.IDMAGASIN,
       f.IDDEVISE,
       f.ESTPREVU,
       f.DATYPREVU,
       nvl(p.MONTANTAR, 0) AS MONTANTPERTEGAIN
FROM FACTUREFOURNISSEUR f
         left JOIN perte_grporigine_fact p ON p.idorigine = f.id;

ALTER TABLE As_BonDeLivraison_Fille ADD pu number(38,2);
ALTER TABLE facturefournisseurfille ADD MONTANTPERTEGAIN number(38,2);

CREATE OR REPLACE  VIEW FF_GRPMERE (IDFACTUREFOURNISSEUR, MONTANTTOTAL, MONTANTPERTEGAIN) AS 
  SELECT
idfacturefournisseur,
sum(qte*pu) AS montanttotal,
sum(MONTANTPERTEGAIN) AS MONTANTPERTEGAIN
FROM facturefournisseurfille
GROUP BY idfacturefournisseur;



CREATE OR REPLACE  VIEW FACTUREFOURNISSEUR_MF (ID, IDFACTUREFOURNISSEUR, IDPRODUIT, QTE, PU, REMISES, IDBCDETAIL, TVA, DEVISE, TAUXDECHANGE, IDDEVISE, DESIGNATION, COMPTE, MONTANTPERTEGAIN, IDFOURNISSEUR, ETAT, DATY) AS 
  SELECT ff.ID,
       ff.IDFACTUREFOURNISSEUR,
       ff.IDPRODUIT,
       ff.QTE,
       ff.PU,
       ff.REMISES,
       ff.IDBCDETAIL,
       ff.TVA,
       ff.DEVISE,
       ff.TAUXDECHANGE,
       ff.IDDEVISE,
       ff.DESIGNATION,
       ff.COMPTE,
       ff.MONTANTPERTEGAIN,
       f.IDFOURNISSEUR,
       f.ETAT,
       f.DATY
FROM FACTUREFOURNISSEURFILLE ff
         JOIN FACTUREFOURNISSEUR f ON ff.IDFACTUREFOURNISSEUR = f.ID;

CREATE OR REPLACE  VIEW FFAVECPERTE_FF (ID, IDFACTUREFOURNISSEUR, IDPRODUIT, QTE, PU, REMISES, IDBCDETAIL, TVA, DEVISE, TAUXDECHANGE, IDDEVISE, DESIGNATION, COMPTE, MONTANTPERTEGAIN, IDFOURNISSEUR, ETAT, DATY, PUPERTEGAIN, MONTANTAVECPERTEGAIN) AS 
  SELECT
	ff.ID,
	ff.IDFACTUREFOURNISSEUR,
	ff.IDPRODUIT,
	ff.QTE,
	ff.PU,
	ff.REMISES,
	ff.IDBCDETAIL,
	ff.TVA,
	ff.DEVISE,
	ff.TAUXDECHANGE,
	ff.IDDEVISE,
	ff.DESIGNATION,
	ff.COMPTE,
	CAST( nvl((CASE WHEN fg.MONTANTPERTEGAIN =0 THEN NULL ELSE  ff.MONTANTPERTEGAIN end),(p.montant*qte*TAUXDECHANGE*pu/fg.montanttotal)) AS NUMBER(30,2) ) AS MONTANTPERTEGAIN ,
	ff.IDFOURNISSEUR,
	ff.ETAT,ff.DATY,
	CAST( (qte*pu*TAUXDECHANGE+nvl((CASE WHEN fg.MONTANTPERTEGAIN =0 THEN NULL ELSE  ff.MONTANTPERTEGAIN end),0))/qte AS NUMBER(30,2) ) AS pupertegain ,
	CAST( (qte*pu*TAUXDECHANGE+nvl((CASE WHEN fg.MONTANTPERTEGAIN =0 THEN NULL ELSE  ff.MONTANTPERTEGAIN end),0)) AS NUMBER(30,2) ) AS montantavecpertegain
FROM
	FACTUREFOURNISSEUR_mf ff
left JOIN perte_grporigine_fact p ON p.idorigine=ff.idfacturefournisseur
LEFT JOIN ff_grpmere fg ON fg.idfacturefournisseur=ff.idfacturefournisseur;

-- GALLOIS_NOUVEAU.FFFILLERESTEALIVRER source

CREATE OR REPLACE  VIEW FFFILLERESTEALIVRER (ID, IDFACTUREFOURNISSEUR, IDPRODUIT, QTE, PU, REMISES, IDBCDETAIL, TVA, IDUNITE, IDPRODUITLIB, UNITELIB, PUPERTEGAIN) AS 
  SELECT f.id,
       f.IDFACTUREFOURNISSEUR,
       f.IDPRODUIT,
       cast(f.QTE - nvl(sum(abf.QUANTITE), 0) as number(38, 2)) AS qte,
       f.PU,
       f.REMISES,
       f.IDBCDETAIL,
       f.TVA,
       au.id as idunite,
       ai.LIBELLE as idproduitlib,
       au.val as unitelib,
       cast(fac.PUPERTEGAIN as number(38, 2)) as PUPERTEGAIN
FROM FACTUREFOURNISSEURFILLE f
         LEFT JOIN AS_BONDELIVRAISON_FILLE abf ON f.ID = abf.IDBC_FILLE
    LEFT JOIN AS_INGREDIENTS ai on ai.id = f.idproduit
    LEFT JOIN AS_UNITE au on au.id = ai.UNITE
    LEFT JOIN FFAVECPERTE_ff fac on fac.id = f.id
GROUP BY f.id, f.IDFACTUREFOURNISSEUR, f.IDPRODUIT, f.QTE, f.PU, f.REMISES, f.IDBCDETAIL, f.TVA, ai.LIBELLE, au.val, au.id, ai.id, fac.PUPERTEGAIN
;



CREATE OR REPLACE  VIEW AS_BONDELIVRAISON_LIBCPL (ID, PRODUIT, NUMBL, QUANTITE, IDDETAILSFACTUREFOURNISSEUR, UNITE, IDBC_FILLE, REMARQUE, IDBC, DATY, ETAT, MAGASIN, PRODUITLIB, UNITELIB, MAGASINLIB, LIBELLEEXTACTE,PU) AS 
  SELECT
	bl.ID,
	bl.PRODUIT,
	bl.NUMBL,
	bl.QUANTITE,
	bl.IDDETAILSFACTUREFOURNISSEUR,
	bl.UNITE,
	bl.IDBC_FILLE,
	AB.REMARQUE,
	AB.IDBC,
	AB.DATY,
	AB.ETAT,
	AB.MAGASIN,
	p.libelle AS PRODUITlib,
	u.VAL AS UNITElib,
	m.VAL AS magasinlib,
	p.LIBELLEEXTACTE,
	bl.pu
FROM
	As_BonDeLivraison_Fille bl
LEFT JOIN AS_BONDELIVRAISON AB ON
	AB.ID = bl.NUMBL
LEFT JOIN AS_INGREDIENTS p ON
	bl.PRODUIT = p.ID
LEFT JOIN AS_UNITE  u ON
	bl.UNITE = u.ID
LEFT JOIN MAGASIN m ON
	ab.MAGASIN = m.ID;