alter table vente add numerofacture varchar2(20);

CREATE OR REPLACE VIEW V_NUMEROFACTURE_EN_COURS AS
SELECT
    EXTRACT(YEAR FROM SYSDATE) AS ANNEE_EN_COURS,
    NVL(MAX(TO_NUMBER(SUBSTR(NUMEROFACTURE, 1, INSTR(NUMEROFACTURE, '/') - 1))), 0) AS DERNIER_NUM,
    NVL(MAX(TO_NUMBER(SUBSTR(NUMEROFACTURE, 1, INSTR(NUMEROFACTURE, '/') - 1))), 0) + 1 AS PROCHAIN_NUM,
    LPAD(NVL(MAX(TO_NUMBER(SUBSTR(NUMEROFACTURE, 1, INSTR(NUMEROFACTURE, '/') - 1))), 0) + 1, 4, '0')
    || '/' || TO_CHAR(EXTRACT(YEAR FROM SYSDATE)) AS PROCHAIN_NUM_FORMAT
FROM VENTE
WHERE SUBSTR(NUMEROFACTURE, INSTR(NUMEROFACTURE, '/') + 1) = TO_CHAR(EXTRACT(YEAR FROM SYSDATE));
