INSERT INTO USERMENU
(ID, REFUSER, IDMENU, IDROLE, CODESERVICE, CODEDIR, INTERDIT)
VALUES('USRMEN0001', NULL, 'MENUDYN00304002', 'magtransitmp', NULL, NULL, 1);
INSERT INTO USERMENU
(ID, REFUSER, IDMENU, IDROLE, CODESERVICE, CODEDIR, INTERDIT)
VALUES('USRMEN0004', NULL, 'MENUDYN00304002', 'magtransiteblg', NULL, NULL, 1);
INSERT INTO USERMENU
(ID, REFUSER, IDMENU, IDROLE, CODESERVICE, CODEDIR, INTERDIT)
VALUES('USRMEN0002', NULL, 'MENUDYN3204004', 'magtransitmp', NULL, NULL, 1);
INSERT INTO USERMENU
(ID, REFUSER, IDMENU, IDROLE, CODESERVICE, CODEDIR, INTERDIT)
VALUES('USRMEN0005', NULL, 'MENUDYN3204004', 'magtransiteblg', NULL, NULL, 1);
INSERT INTO USERMENU
(ID, REFUSER, IDMENU, IDROLE, CODESERVICE, CODEDIR, INTERDIT)
VALUES('USRMEN0003', NULL, 'MENUDYN00304001', 'magtransitmp', NULL, NULL, NULL);
INSERT INTO USERMENU
(ID, REFUSER, IDMENU, IDROLE, CODESERVICE, CODEDIR, INTERDIT)
VALUES('USRMEN0006', NULL, 'MENUDYN00304001', 'magtransiteblg', NULL, NULL, NULL);

INSERT INTO MENUDYNAMIQUE
(ID, LIBELLE, ICONE, HREF, RANG, NIVEAU, ID_PERE)
VALUES('MNDN00000002113', 'D&eacute;part', 'fa fa-list', 'module.jsp?but=stock/transfertstock/transfertstock-depart-liste.jsp', 3, 3, 'MNDN0000000211');
INSERT INTO MENUDYNAMIQUE
(ID, LIBELLE, ICONE, HREF, RANG, NIVEAU, ID_PERE)
VALUES('MNDN00000002114', 'Arriv&eacute;', 'fa fa-list', 'module.jsp?but=stock/transfertstock/transfertstock-arrive-liste.jsp', 4, 3, 'MNDN0000000211');
INSERT INTO MENUDYNAMIQUE
(ID, LIBELLE, ICONE, HREF, RANG, NIVEAU, ID_PERE)
VALUES('MNDN0000000031', 'Demande de transfert', 'fa fa-file', NULL, 10, 2, 'MNDN000000003');
INSERT INTO MENUDYNAMIQUE
(ID, LIBELLE, ICONE, HREF, RANG, NIVEAU, ID_PERE)
VALUES('MNDN0000000032', 'Saisie', 'fa fa-plus', 'module.jsp?but=demande/demandetransfert-saisie.jsp', 1, 3, 'MNDN0000000031');
INSERT INTO MENUDYNAMIQUE
(ID, LIBELLE, ICONE, HREF, RANG, NIVEAU, ID_PERE)
VALUES('MNDN0000000033', 'Liste', 'fa fa-list', 'module.jsp?but=demande/demandetransfert-liste.jsp', 2, 3, 'MNDN0000000031');