CREATE OR REPLACE VIEW MAGASINPOINT AS 
 SELECT 
    m.ID AS ID,
    m.VAL,
    m.DESCE,
    m.IDPRODUIT,
    m.IDTYPEMAGASIN,
    m.IDPOINT,
    m.ETAT
FROM MAGASIN2 m

UNION

SELECT 
    p.ID AS ID,
    p.VAL,
    p.DESCE,
    NULL AS IDPRODUIT,
    NULL AS IDTYPEMAGASIN,
    p.ID AS IDPOINT,
    11 AS ETAT
FROM POINT p
WHERE p.ID NOT IN (
    SELECT m.IDPOINT FROM MAGASIN2 m WHERE m.IDPOINT IS NOT NULL
)
;

CREATE OR REPLACE VIEW AS_INGREDIENTS_MAGASIN AS
  SELECT
	ai."ID",ai."LIBELLE",ai."SEUIL",ai."UNITE",ai."QUANTITEPARPACK",ai."PU",ai."ACTIF",ai."PHOTO",ai."CALORIE",ai."DURRE",ai."COMPOSE",ai."CATEGORIEINGREDIENT",ai."IDFOURNISSEUR",ai."DATY",ai."QTELIMITE",ai."PV",ai."LIBELLEVENTE",ai."SEUILMIN",ai."SEUILMAX",ai."PUACHATUSD",ai."PUACHATEURO",ai."PUACHATAUTREDEVISE",ai."PUVENTEUSD",ai."PUVENTEEURO",ai."PUVENTEAUTREDEVISE",ai."ISVENTE",ai."ISACHAT",ai."COMPTE_VENTE",ai."COMPTE_ACHAT",ai."LIBELLEEXTACTE",ai."TVA",ai."FILEPATH",ai."RESTE",ai."TYPESTOCK",
	m.ID  AS IDMAGASIN
FROM
	AS_INGREDIENTS ai ,
	MAGASINPOINT m ;
    

CREATE OR REPLACE VIEW V_ETATSTOCK_ING_MAGASIN AS
SELECT 
    aim.ID AS ID,
    p.LIBELLE AS idproduitLib,
    p.CATEGORIEINGREDIENT,
    tp.DESCE AS idtypeproduitlib,
    aim.IDMAGASIN,
    mag.DESCE AS idmagasinlib,
    NVL(MAX(m.DATY),TO_DATE('01-01-2001', 'DD-MM-YYYY')) AS dateDernierMouvement,
    CAST(SUM(NVL(f.ENTREE, 0)) - SUM(NVL(f.SORTIE, 0)) AS NUMBER(30,2)) AS QUANTITE,
    CAST(SUM(NVL(f.ENTREE, 0)) AS NUMBER(30,2)) AS ENTREE,
    CAST(SUM(NVL(f.SORTIE, 0)) AS NUMBER(30,2)) AS SORTIE,
    CAST(SUM(NVL(f.ENTREE, 0)) - SUM(NVL(f.SORTIE, 0)) AS NUMBER(30,2)) AS reste,
    p.UNITE,
    u.DESCE AS idunitelib,
    CAST(NVL(p.PV, 0) AS NUMBER(30, 2)) AS PUVENTE,
    mag.IDPOINT,
    mag.IDTYPEMAGASIN,
    p.SEUILMIN,
    p.SEUILMAX,
    pt.VAL AS idPointLib 
FROM AS_INGREDIENTS_MAGASIN aim
LEFT JOIN AS_INGREDIENTS p ON aim.ID = p.ID
LEFT JOIN CATEGORIEINGREDIENT tp ON p.CATEGORIEINGREDIENT = tp.ID
LEFT JOIN MAGASINPOINT mag ON aim.IDMAGASIN = mag.ID
LEFT JOIN AS_UNITE u ON p.UNITE = u.ID
LEFT JOIN MVTSTOCK m ON m.IDMAGASIN = aim.IDMAGASIN AND m.ETAT = 11
LEFT JOIN MVTSTOCKFILLE f ON f.IDMVTSTOCK = m.ID AND f.IDPRODUIT = aim.ID
LEFT JOIN POINT pt ON pt.ID = mag.IDPOINT
GROUP BY 
    aim.ID, 
    p.LIBELLE, 
    p.CATEGORIEINGREDIENT,
    tp.DESCE,
    aim.IDMAGASIN,
    mag.DESCE,
    p.UNITE,
    u.DESCE,
    p.PV,
    mag.IDPOINT,
    mag.IDTYPEMAGASIN,
    p.SEUILMIN,
    p.SEUILMAX,
	pt.VAL;

CREATE OR REPLACE VIEW V_ETATSTOCK_ING_POINT AS 
  SELECT 
    aim.ID AS ID,
    p.LIBELLE AS idproduitLib,
    p.CATEGORIEINGREDIENT,
    tp.DESCE AS idtypeproduitlib,
    NVL(MAX(m.DATY),TO_DATE('01-01-2001', 'DD-MM-YYYY')) AS dateDernierMouvement,
    CAST(SUM(NVL(f.ENTREE, 0)) - SUM(NVL(f.SORTIE, 0)) AS NUMBER(30,2)) AS QUANTITE,
    CAST(SUM(NVL(f.ENTREE, 0)) AS NUMBER(30,2)) AS ENTREE,
    CAST(SUM(NVL(f.SORTIE, 0)) AS NUMBER(30,2)) AS SORTIE,
    CAST(SUM(NVL(f.ENTREE, 0)) - SUM(NVL(f.SORTIE, 0)) AS NUMBER(30,2)) AS reste,
    p.UNITE,
    u.DESCE AS idunitelib,
    CAST(NVL(p.PV, 0) AS NUMBER(30, 2)) AS PUVENTE,
    mag.IDPOINT,
    p.SEUILMIN,
    p.SEUILMAX,
    pt.VAL AS idPointLib
FROM AS_INGREDIENTS_MAGASIN aim
LEFT JOIN AS_INGREDIENTS p ON aim.ID = p.ID
LEFT JOIN CATEGORIEINGREDIENT tp ON p.CATEGORIEINGREDIENT = tp.ID
LEFT JOIN MAGASINPOINT mag ON aim.IDMAGASIN = mag.ID
LEFT JOIN AS_UNITE u ON p.UNITE = u.ID
LEFT JOIN MVTSTOCK m ON m.IDMAGASIN = aim.IDMAGASIN AND m.ETAT = 11
LEFT JOIN MVTSTOCKFILLE f ON f.IDMVTSTOCK = m.ID AND f.IDPRODUIT = aim.ID
LEFT JOIN POINT pt ON pt.ID = mag.IDPOINT
GROUP BY 
    aim.ID, 
    p.LIBELLE, 
    p.CATEGORIEINGREDIENT,
    tp.DESCE,
    p.UNITE,
    u.DESCE,
    p.PV,
    mag.IDPOINT,
    p.SEUILMIN,
    p.SEUILMAX,
  	pt.VAL;