CREATE OR REPLACE VIEW V_ETATSTOCK_ENTREE AS 
  SELECT
  	ve.id,
	ai.id AS IDPRODUIT ,
	ai.LIBELLE AS idproduitlib,
	ai.CATEGORIEINGREDIENT ,
	c.VAL AS idtypeproduitlib,
	ve.IDMAGASIN,
	m.VAL AS idmagasinlib,
	ve.QUANTITE ,
	ve.ENTREE ,
	ve.SORTIE ,
	ve.RESTE ,
	ai.UNITE ,
	u.VAL AS idunitelib,
	ve.PU,
	ve.DATY
FROM
	MVTSTOCKENTREEAVECRESTE2 ve
LEFT JOIN AS_INGREDIENTS ai ON
	ai.id = ve.IDPRODUIT
LEFT JOIN CATEGORIEINGREDIENT c ON
	ai.CATEGORIEINGREDIENT = c.id
LEFT JOIN MAGASINPOINT m ON
	ve.IDMAGASIN = m.id
LEFT JOIN AS_UNITE u ON ai.UNITE = u.id;


ALTER TABLE TRANSFERTSTOCKDETAILS ADD pu number(30, 2);

DELETE FROM AS_UNITE WHERE ID='UNT001106';


CREATE OR REPLACE VIEW TRANSFERTSTOCKDETAILSCPL AS
SELECT
    t.ID ,
    t.IDTRANSFERTSTOCK ,
    t2.DESIGNATION AS IDTRANSFERTSTOCKLIB,
    t.IDPRODUIT ,
    p.libelle AS IDPRODUITLIB,
    CAST (t.QUANTITE AS NUMBER(30,2)) AS QUANTITE
FROM TRANSFERTSTOCKDETAILS t
         LEFT JOIN TRANSFERTSTOCK t2 ON t2.ID = t.IDTRANSFERTSTOCK
         LEFT JOIN AS_INGREDIENTS  p ON p.ID = t.IDPRODUIT;


ALTER TABLE TRANSFERTSTOCKDETAILS ADD QUANTITETEMP NUMBER(30,2);

UPDATE TRANSFERTSTOCKDETAILS SET QUANTITETEMP = QUANTITE WHERE 1=1;

ALTER TABLE TRANSFERTSTOCKDETAILS DROP COLUMN QUANTITE ;

ALTER TABLE TRANSFERTSTOCKDETAILS RENAME COLUMN QUANTITETEMP TO QUANTITE ;

CREATE OR REPLACE VIEW V_ETATSTOCK_ENTREE AS
SELECT
    ve.id,
    ai.id AS IDPRODUIT ,
    ai.LIBELLE AS idproduitlib,
    ai.CATEGORIEINGREDIENT ,
    c.VAL AS idtypeproduitlib,
    ve.IDMAGASIN,
    m.VAL AS idmagasinlib,
    ve.QUANTITE ,
    ve.ENTREE ,
    ve.SORTIE ,
    ve.RESTE ,
    ai.UNITE ,
    u.VAL AS idunitelib,
    ve.PU,
    ve.DATY
FROM
    MVTSTOCKENTREEAVECRESTE2 ve
        LEFT JOIN AS_INGREDIENTS ai ON
        ai.id = ve.IDPRODUIT
        LEFT JOIN CATEGORIEINGREDIENT c ON
        ai.CATEGORIEINGREDIENT = c.id
        LEFT JOIN MAGASIN2 m ON
        ve.IDMAGASIN = m.id
        LEFT JOIN UNITE u ON ai.UNITE = u.id;