CREATE OR REPLACE VIEW INVENTAIREFILLEMERE AS
SELECT
	i.*,
	i2.IDMAGASIN
FROM
	INVENTAIREFILLE i
JOIN INVENTAIRE i2 ON
	i.IDINVENTAIRE = i2.ID 
WHERE ETAT>0;

CREATE OR REPLACE VIEW INVENTAIREFILLECOMPLET AS
SELECT
	i.*,
	vee.RESTE , vee.MVTSRC AS mvtentree
FROM
	INVENTAIREFILLEMERE i
LEFT JOIN V_ETATSTOCK_PU vee ON
	vee.ID = i.IDPRODUIT
	AND vee.pu = i.PU
	AND i.IDMAGASIN = vee.IDMAGASIN ;

UPDATE AS_INGREDIENTS ai
SET ai.PU = (
    SELECT putemp
    FROM PRIXTEMP v
    WHERE v.IDPRODUIT = ai.ID
); 
UPDATE AS_INGREDIENTS ai
SET ai.RESTE = (
    SELECT SUM(v.reste)
    FROM V_ETATSTOCK_ING v
    WHERE v.ID = ai.ID
);

CREATE OR REPLACE  VIEW "INVENTAIREFILLELIB" AS
  SELECT
i.ID ,
i.IDINVENTAIRE ,
i.IDPRODUIT ,
p.libelle AS IDPRODUITLIB,
i.EXPLICATION ,
i.QUANTITETHEORIQUE ,
i.QUANTITE,
p.LIBELLEEXTACTE,
i.pu,
(i.QUANTITE - i.QUANTITETHEORIQUE) AS ecart
FROM INVENTAIREFILLE i
LEFT JOIN AS_INGREDIENTS  p ON p.ID  = i.IDPRODUIT;
